### ISSUE TITLE
azure-iot-samples-python-master error

### ISSUE THREAD

**Issue by Kirill095** [Azure/azure-iot-sdk-python#146] opened 2018-06-04 20:40 UTC
Hi,

I have just installed Python 3.7.0b4 in a Windows 10 machine.
I successfully installed packages
azure-iothub-device-client == 1.3.5
azure-iothub-service-client == 1.3.5

but I get the following error on execution:

d: \ python37 \ Scripts> python.exe D: \ pyton \ azureiot \ azure-iot-samples-python-master \ iot-hub \ Quickstarts \ simulated-device \ SimulatedDevice.py
Traceback (most recent last call last):
   File "D: \ pyton \ azureiot \ azure-iot-samples-python-master \ iot-hub \ Quickstarts \ simulated-device \ SimulatedDevice.py", line 11, in <module>
     import iothub_client
   File "D: \ python37 \ lib \ site-packages \ iothub_client \ __ init__.py", line 1, in <module>
     from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

I will be grateful for help

**Comment by yzhong94** [comment] 2018-06-20 17:08
Can you check whether the Python installer is for x64 or x32?  Please take a look at this guide for more info: https://azure.microsoft.com/en-us/blog/iot-python-sdk-troubleshoot/

You can uninstall your current Python, go to Python.org to download the correct version, and try again.

**Comment by pierreca** [comment] 2018-07-02 21:51
@Kirill095 closing since we think the issue is solved with @yzhong94's suggestion. if not feel free to reopen the issue.

**Closed by pierreca** 2018-07-02 21:51 UTC
