### ISSUE TITLE
cross-compile issues

### ISSUE THREAD

**Issue by wushichuan** [Azure/azure-iot-sdk-python#43] opened 2017-06-14 02:46 UTC
- **OS and version used:**
openwrt 10.03

- **Python runtime used:** 
2.7.12

- **SDK version used:** <VERSION> 
azure-iot-sdk-python

# Description of the issue:
Enconter errs while cross-compile，
make[2]: *** [python/test/CMakeFiles/iothub_client_mock.dir/__/src/iothub_client_python.cpp.o] Error 1
make[1]: *** [python/test/CMakeFiles/iothub_client_mock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/__/src/iothub_service_client_python.cpp.o] Error 1
make[1]: *** [python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/all] Error 2
make: *** [all] Error 2

# Code sample exhibiting the issue:
 ./build.sh --toolchain-file toolchain-openwrt.cmake -cl -ldl

# Console log of the issue:
[ 40%] Building C object iothub_client/CMakeFiles/iothub_client.dir/src/iothubtransport.c.o
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:734:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:734:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubServiceClientAuthHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubServiceClientAuth::IoTHubServiceClientAuth(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:742:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubServiceClientAuth::Destroy()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:759:13: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'IOTHUB_SERVICE_CLIENT_AUTH_TAG* IoTHubServiceClientAuth::GetHandle()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:768:16: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: At global scope:
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:832:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:832:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubServiceClientAuthHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:833:66: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:833:66: error: 'constexpr' needed for in-class initialization of static data member '_iothubRegistryManagerHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubRegistryManager::IoTHubRegistryManager(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:843:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:849:9: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubRegistryManager::IoTHubRegistryManager(IoTHubServiceClientAuth)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:863:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope[ 41%] Building C object uamqp/CMakeFiles/uamqp.dir/src/header_detect_io.c.o

/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:869:9: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubRegistryManager::Destroy()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:886:13: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:892:13: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'IOTHUB_DEVICE IoTHubRegistryManager::CreateDevice(std::string, std::string, std::string, IOTHUB_REGISTRYMANAGER_AUTH_METHOD)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:918:53: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'IOTHUB_DEVICE IoTHubRegistryManager::GetDevice(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:935:50: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubRegistryManager::UpdateDevice(std::string, std::string, std::string, IOTHUB_DEVICE_STATUS, IOTHUB_REGISTRYMANAGER_AUTH_METHOD)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:962:53: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubRegistryManager::DeleteDevice(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:977:53: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'boost::python::list IoTHubRegistryManager::GetDeviceList(size_t)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:994:54: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'IOTHUB_REGISTRY_STATISTICS IoTHubRegistryManager::GetStatistics()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1022:54: error: '_iothubRegistryManagerHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: At global scope:
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1220:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1220:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubServiceClientAuthHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1221:61: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1221:61: error: 'constexpr' needed for in-class initialization of static data member '_iothubMessagingHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1222:48: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1222:48: error: 'constexpr' needed for in-class initialization of static data member 'openCompleteContext' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1223:48: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1223:48: error: 'constexpr' needed for in-class initialization of static data member 'sendCompleteContext' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1224:62: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1224:62: error: 'constexpr' needed for in-class initialization of static data member 'feedbackMessageContext' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::CreateContexts()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1228:13: error: 'openCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1230:13: error: 'sendCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1232:13: error: 'feedbackMessageContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::DestroyContexts()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1238:13: error: 'openCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1240:39: error: type '<type error>' argument given to 'delete', expected pointer
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1242:13: error: 'sendCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1244:39: error: type '<type error>' argument given to 'delete', expected pointer
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1246:13: error: 'feedbackMessageContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1248:42: error: type '<type error>' argument given to 'delete', expected pointer
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubMessaging::IoTHubMessaging(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1259:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1265:9: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubMessaging::IoTHubMessaging(IoTHubServiceClientAuth)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1280:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1286:9: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::Destroy()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1304:13: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1310:13: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::Open(boost::python::api::object&, boost::python::api::object&)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1324:13: error: 'openCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1331:39: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1331:85: error: 'openCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::Close()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1343:31: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::SendAsync(std::string, IoTHubMessage&, boost::python::api::object&, boost::python::api::object&)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1354:13: error: 'sendCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1361:44: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1361:126: error: 'sendCompleteContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubMessaging::SetFeedbackMessageCallback(boost::python::api::object&, boost::python::api::object&)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1375:13: error: 'feedbackMessageContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1382:61: error: '_iothubMessagingHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1382:118: error: 'feedbackMessageContext' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: At global scope:
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1445:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1445:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubServiceClientAuthHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1446:76: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1446:76: error: 'constexpr' needed for in-class initialization of static data member '_iothubDeviceMethodHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubDeviceMethod::IoTHubDeviceMethod(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1455:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1461:9: error: '_iothubDeviceMethodHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubDeviceMethod::IoTHubDeviceMethod(IoTHubServiceClientAuth)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1475:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1481:9: error: '_iothubDeviceMethodHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubDeviceMethod::Destroy()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1498:13: error: '_iothubDeviceMethodHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1504:13: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'IoTHubDeviceMethodResponse IoTHubDeviceMethod::Invoke(std::string, std::string, std::string, unsigned int)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1525:44: error: '_iothubDeviceMethodHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: At global scope:
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1590:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1590:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubServiceClientAuthHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1591:72: sorry, unimplemented: non-static data member initializers
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1591:72: error: 'constexpr' needed for in-class initialization of static data member '_iothubDeviceTwinHandle' of non-integral type
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubDeviceTwin::IoTHubDeviceTwin(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1600:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1606:9: error: '_iothubDeviceTwinHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In constructor 'IoTHubDeviceTwin::IoTHubDeviceTwin(IoTHubServiceClientAuth)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1620:9: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1626:9: error: '_iothubDeviceTwinHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'void IoTHubDeviceTwin::Destroy()':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1643:13: error: '_iothubDeviceTwinHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1649:13: error: '_iothubServiceClientAuthHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'std::string IoTHubDeviceTwin::GetTwin(std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1664:45: error: '_iothubDeviceTwinHandle' was not declared in this scope
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: In member function 'std::string IoTHubDeviceTwin::UpdateTwin(std::string, std::string)':
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1687:48: error: '_iothubDeviceTwinHandle' was not declared in this scope

**Comment by tameraw** [comment] 2017-06-26 16:45
@wushichuan - Thanks for filing this issue. We'll investigate it.

**Comment by markrad** [comment] 2017-06-26 17:42
Hi @wushichuan,

I'm not sure why you are seeing a cross compile error for OpenWrt. However, before we try and debug this I will need you to test something for me. 

I successfully cross compiled the Azure IoT Hub Python library for OpenWrt but when I attempted to run it I found that the Python "Light" that is typically installed on OpenWrt devices does **not support binary Python libraries.** I would like you to cross compile a simple Python binary library. There are many samples on the Internet. Try and run that on your device. If it fails then you will need to consider cross compiling Python for your platform before we even address this issue. You may not have enough resources to run the complete Python package on your device which means you will need to use the C SDK instead. 

Let me know what you find.

_Mark Radbourne MSFT_

**Comment by wushichuan** [comment] 2017-06-27 02:38
Hi @markrad ,
Thanks for your reply, Accroding to you advices, I had cross compiled some python binary libs, just like psutils, apscheduler, multiprocessing, pymodbus and some other related libs,  and they work well. I should use the interfaces of libs in the python2.7 evironment, maybe the resources is enough. I had cross-compiled then C SDK version sucessfully, but failed with python SDK version.

**Comment by markrad** [comment] 2017-06-29 20:28
Hi @wushichuan,

Do you know what versions of gcc and g++ you are running? The error messages are caused by a coding construct that is not supported by your compiler. It does not allow initialization of non-static member variables in a class. For example:

Error message:
```
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp: At global scope:
/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:1590:72: sorry, unimplemented: non-static data member initializers
```

Failing code:

```cpp
class IoTHubDeviceTwin
{
    IOTHUB_SERVICE_CLIENT_AUTH_HANDLE _iothubServiceClientAuthHandle = NULL;
    IOTHUB_SERVICE_CLIENT_DEVICE_TWIN_HANDLE _iothubDeviceTwinHandle = NULL;
public:
'''
}
```

Your compiler is complaining about the assignment of NULL to these variables. It wants you to initialize them in the constructor. This would not be a difficult change for you to make to get you unblocked. I can discuss with the product team a more permanent solution.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-07-14 22:05
Hi @wushichuan,

The product group have merged a fix to address this issue. All non-static class member variables are now initialized in the constructors. You should no longer see this issue.

_Mark Radbourne MSFT_

**Closed** 2017-07-14 22:09 UTC
Labels: CSS, port issue
