### ISSUE TITLE
Cannot publish behind a proxy

### ISSUE THREAD

**Issue by simdoo** [Azure/azure-iot-sdk-python#125] opened 2018-03-08 14:32 UTC
- **OS and version used:** <VERSION>  Raspbian 9.3 

- **Python runtime used:** <VERSION>  Python3.6.0 & 2.7.13

# Description of the issue:

I can't connect to the hub when I am behind a proxy. Is there no option to add a proxy parameter in the code
# Code sample exhibiting the issue:

pip3 install azure-iothub-device-client
python3 iothub_client_sample.py

# Console log of the issue:

Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:631 Failure: getaddrinfo failure -2.
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:751 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed opening the underlying I/O.
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/c-utility/src/uws_client.c Func:uws_client_open_async Line:1480 Opening the underlying IO failed
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/c-utility/src/wsio.c Func:wsio_open Line:510 Opening the uws instance failed.
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Thu Mar  8 15:12:57 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1787 failure connecting to address myiothub.azure-devices.net.

**Comment by zolvarga** [comment] 2018-03-09 18:31
@simdoo 

Thank you for reporting this. It is a missing option in the device client.
We are going to implement it and as soon as it checked in will let you know.

Best Regards,
Zoltan

**Comment by alex78mw** [comment] 2018-03-27 09:51
Hello @zolvarga still no solution to publish behind a proxy ? 
I don't understand the purpose of iothub_client_options.h file I thought it was for the proxy setting... ?

**Comment by zolvarga** [comment] 2018-05-24 18:26
@simdoo 

Could you please make sure you set the "proxy_data" with "set_option" from Python?
Please let me know...

Best Regards,
Zoltan

**Comment by simdoo** [comment] 2018-05-25 11:49
@zolvarga 

In azure-iot-sdk-python/device/samples/iothub_client_sample.py 
I tried to add client.set_option("proxy_data", PROXY) after set_certificates(client)
With PROXY="http://user:password@address:port"

With HTTP as protocol :
I have an Segmentation fault error

With MQTT_WS as protocol :
Error: Time:Fri May 25 13:46:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:IoTHubTransport_MQTT_Common_SetOption Line:2843 Cannot set proxy option once the underlying IO is created
Error: Time:Fri May 25 13:46:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1790 unable to IoTHubTransport_SetOption
Error: Time:Fri May 25 13:46:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client.c Func:IoTHubClient_SetOption Line:1506 IoTHubClient_LL_SetOption failed
IoTHub Client SetOption failed with result: 2Error: Time:Fri May 25 13:46:41 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -2.

**Comment by pierreca** [comment] 2018-07-03 21:53
@simdoo
sorry for the late response, I'm revisiting those issues.
if that is still an issue can you please paste a code snippet showing how you create the client and call setOptions? 

thanks!

**Comment by pierreca** [comment] 2018-07-17 03:56
@simdoo closing due to lack of activity - please free to reopen if there's still interest in solving this issue. Thanks!

**Comment by haimiko** [comment] 2018-08-15 18:15
Same here. Still an issue.  I get a segmentation fault as well.

**Comment by pierreca** [comment] 2018-08-15 21:38
@haimiko and just to make sure I understand you get:
- a segfault when using HTTP?
- a setoption error when using MQTT-WS?

Can you paste a snippet of code that reproduces the issue?

**Comment by pierreca** [comment] 2018-08-23 17:51
This is followed up on #174. closing this one as duplicate.

**Comment by az-iot-builder-01** [comment] 2018-08-23 17:51
@alex78mw, @simdoo, @haimiko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2018-08-23 17:51 UTC
Labels: investigation-required, raspbian
