### ISSUE TITLE
azure-iothub-device-client==1.4.0.0b2 not respect EdgeHubConnectionString/EdgeModuleCertificatefile environment variables

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-python#150] opened 2018-06-25 08:17 UTC
Try to run azure-iothub-device-client==1.4.0.0b2 (with create_from_environment) on IoT Edge Public Preview runtime, but meet with below errors:
![image](https://user-images.githubusercontent.com/1050213/41838469-1716c170-7893-11e8-928c-ae2c5eaa7bff.png)
From the log (certificate verify failed), it seems that the new SDK dose not respect EdgeModuleCertificatefile which leads to the failure.

**Comment by jspaith** [comment] 2018-07-03 23:45
The C SDK which Python is built on is going to have a lot of difficulty with the EdgeModuleCertificatefile concept, because it has 0 filesystem dependencies.  Adding filesystem dependencies really isn't something we want to do, since we'd have to plumb up into the PAL layer and add fair amount of complexity for this.

If a client - let's just say Visual Studio Code - wanted to interact in this model, it'd be very helpful if it could create a new environment variable called "EdgeModuleCertificateContent" where the contents of the cert were set directly into that variable.  If we could do that, the C SDK (and Python for free) could very easily just get this variable and set it into our trusted root.  For openssl based clients.

**Comment by jspaith** [comment] 2018-07-03 23:51
Also as an unpleasant but serviceable workaround, the caller could itself query this value, read the file in, and then set option on  "TrustedCerts".  We prefer closer collaboration between the SDK & VS Code with the proposed fix above, however, for long-term solution.

**Comment by OwenYangECS** [comment] 2019-02-03 02:56
@jspaith 
I have same error with different scenario:
there are two module run up on Azure  IoT edge environment,
one built from C# and other one from Python,
C# one send commands to Python one base on itself schedule design.
And Python one receive command and response will occur same error "certificate verify failed" probability,
when this error happening Python one will stop and did't restart again.

these error are same root cause?

please show some modification detail for "EdgeModuleCertificateContent".

thanks.

**Comment by jspaith** [comment] 2019-02-04 17:44
@OwenYangECS  - please open up a new GitHub issue here for this, since we don't really tracked closed ones.

It will really help if you can enable full logging here, something along lines of below.  

```python
iothub_device_client.set_option("logtrace", 1)
```

And also the simpliest possible sample code of Python that repros the problem.

Also note that the EdgeModuleCertificatefile discussed here is specific if you're trying to debug the Python in a proper debugger, and in paritcular trying to do a connection_string based creation.  

If you're using one of samples from `iothub_client_sample_invoke_module.py` or `iothub_client_sample_module_filter.py` or `iothub_client_sample_module_sender.py` directly and inside a Docker container, then the `create_from_environment` should in theory handle all the work here for you.

**Comment by jspaith** [comment] 2019-02-04 17:44
Closing to create a new thread.

**Comment by az-iot-builder-01** [comment] 2019-02-04 17:44
@formulahendry, @OwenYangECS, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-02-04 17:44 UTC
Labels: area-c-sdk, enhancement
