### ISSUE TITLE
Twin device callback reports payload differently

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-iot-sdk-python#182] opened 2018-08-22 10:54 UTC
Maybe I am missing something but can someone point me to the regarding documentation where I can find an explanation what the payload parameter of that callback holds. My app runs on a client device and I am trying to replicate the fw update scenario. Depending on the performed action the callback provides different fields in its payload message.

First callback that was triggered after I changed the _reported_ property from the device app included _desired_ and _reported_ fields
```
Twin callback called with:
    updateStatus: COMPLETE
    payload: {
  "desired": {
    "test": 1,
    "telemetryInterval": 120,
    "hallo": 123,
    "$version": 6
  },
  "reported": {
    "connectivity": "cellular",
    "currentFwVersion": "",
    "pendingFwVersion": "1.2.3",
    "fwUpdateStatus": "downloading",
    "fwUpdateSubstatus": "",
    "lastFwUpdateStartTime": "2018-08-22T10:10:10.437789Z",
    "lastFwUpdateEndTime": "",
    "$version": 5
  }
}
```

but the second callback which got triggered by a remote change from the backend only include the _desired_ message even without the _key_

```
Twin callback called with:
    updateStatus: PARTIAL
    payload: {
  "test": 1,
  "telemetryInterval": 120,
  "hallo": 123,
  "$version": 7
}
```

Why does it get invoked with different messages? And how can I know when it has both fields and when not.

Win 10 Enterprise
Python 3.6.6
azure-iothub-device-client 1.4.2

**Comment by pierreca** [comment] 2018-08-23 02:28
@Bnjmn83 

the callback is called with `updateStatus` set to `COMPLETE` initially when the twin callback is set, so that you have a full twin object to start with. All subsequent updates are `PARTIAL` and you will receive only desired properties updates. This is by design to save on bandwidth considering that you "know" all reported properties updates already, since the device is generating them and the service cannot write to that part of the twin.

Does that make sense? What behavior would you expect?

**Comment by Bnjmn83** [comment] 2018-08-23 11:54
it makes sense to me. Where is the regarding part in the documentation?

**Comment by pierreca** [comment] 2018-08-23 17:48
we've had issues with docs.microsoft.com getting our API docs published - I guess this is where it should go but we don't call this out explicitely
https://github.com/Azure/azure-iot-sdk-python/blob/master/device/iothub_client_python/iothub_client_python.py#L619

we could certainly clarify that paragraph so that it's ready when we fix the interop with docs.microsoft.com

**Comment by Bnjmn83** [comment] 2018-08-27 08:33
I found that part myself but for an API description it lacks too many information!

**Comment by jebrando** [comment] 2020-01-02 19:24
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment] 2020-01-02 19:24
@Bnjmn83, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by jebrando** 2020-01-02 19:24 UTC
Labels: area-documentation, device-client, fixed-in-v2, v1-deprecated
