### ISSUE TITLE
Not returning an IoTHubMessageDispositionResult to the message_receive_callback crashes the python process

### ISSUE THREAD

**Issue by alex007sirois** [Azure/azure-iot-sdk-python#180] opened 2018-08-21 19:03 UTC
- **OS and version used:** <VERSION>
Raspberry Pi 3 Model B+ 
Raspbian GNU/Linux 9 (stretch)
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

- **Python runtime used:** <VERSION>
Python 2.7.13

- **SDK version used:** <VERSION>
azure-iothub-device-client==1.4.2
libboost1.62-all

# Description of the issue:
When registering a callback for the reception of message, we MUST return a IoTHubMessageDispositionResult or else the whole python process crashes with Segmentation fault. This includes raising an exception. The same behavior is found using MQTT, MQTT_WS, AMQP and AMQP_WS (did not try HTTP as we would never use it to receive messages).  Doing the same code sample but returning any IoTHubMessageDispositionResult value will work. If there is no return, it implicitly return None and crash.

This is probably the line that makes the segmentation fault: https://github.com/Azure/azure-iot-sdk-python/blob/0a549f21f7f4fc24bc036c1d2d5614e9544a9667/device/iothub_client_python/src/iothub_client_python.cpp#L1017

# Code sample exhibiting the issue:
```
from iothub_client import IoTHubClient, IoTHubTransportProvider, IoTHubMessageDispositionResult

connection_string = "connection string"
protocol = IoTHubTransportProvider.MQTT
client = IoTHubClient(connection_string, protocol)

def receive_message_callback(message, user_context): pass

client.set_message_callback(receive_message_callback, 0)
```
Then going to the azure portal and sending a message to the device.
# Console log of the issue:
```
Segmentation fault
```
but using gdb to get the backtrace:
```
#0  0x000a7bcc in PyObject_IsInstance ()
#1  0x766d2914 in boost::python::enum_<IOTHUBMESSAGE_DISPOSITION_RESULT_TAG>::convertible_from_python(_object*) () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#2  0x76536f04 in boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&) () from /usr/lib/arm-linux-gnueabihf/libboost_python-py27.so.1.62.0
#3  0x766d0a58 in boost::python::converter::extract_rvalue<IOTHUBMESSAGE_DISPOSITION_RESULT_TAG>::extract_rvalue(_object*) () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#4  0x766ca53c in boost::python::extract<IOTHUBMESSAGE_DISPOSITION_RESULT_TAG>::extract(boost::python::api::object const&) () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#5  0x766bff04 in ReceiveMessageCallback () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#6  0x767209cc in dispatch_user_callbacks () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#7  0x76720f60 in ScheduleWork_Thread () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#8  0x767ce1a0 in ThreadWrapper () from /usr/local/lib/python2.7/dist-packages/iothub_client/iothub_client.so
#9  0x76f56fc4 in start_thread (arg=0x75717450) at pthread_create.c:335
#10 0x76e16bc8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by pierreca** [comment] 2018-08-22 21:08
@alex007sirois my understanding is that it's because it's mandatory to return a disposition status, otherwise the IoT hub does not know if the message was acknowledged or not and therefore will try to resend it. I'll ask around but I'm tempted to say this is probably by design...
what behavior would you expect?

**Comment by alex007sirois** [comment] 2018-08-23 13:00
I understand that it's mandatory to return a disposition status, but if there is an exception encountered (in this case, a TypeError), the exception should be raised/logged. There should never be a Segmentation fault in python as the process crash, there is no traceback, no error message and I cannot gracefully close anything.

I just want the lib to try/catch this and put the error in log like every other errors.

**Comment by pierreca** [comment] 2018-08-23 17:12
Oohh I see what you're saying. thanks for clarifying. We'll take a closer look.

**Comment by nymix** [comment] 2019-03-13 15:35
Hi there, I'm running afoul of the same issue and have been wondering if there has been any progress made on its resolution? Alternatively if there is a work around, I would greatly appreciate that too.

**Comment by jebrando** [comment] 2019-12-18 15:44
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK.  We will be closing the v1 SDK issues whose features are covered by the v2 release.  Feel free to open an new issue if you find an issue with the v2 SDK.

Thank you for your patronage

**Comment by az-iot-builder-01** [comment] 2019-12-18 15:44
@alex007sirois, @nymix, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-12-18 15:44 UTC
Labels: area-boost-wrapper, investigation-required, v1-deprecated
