### ISSUE TITLE
Install into a virtual environment or using pyenv?

### ISSUE THREAD

**Issue by mattdodge** [Azure/azure-iot-sdk-python#154] opened 2018-07-10 01:47 UTC
First off, I'm trying to install this on a Mac so I'm having to jump through four thousand different hoops to even get that working. So far I have been unsuccessful. 

I think that part of the problem is that I am trying to install into a virtual environment, specifically one using pyenv. The problem with this seems to be that all of the Mac installation scripts seem to assume your python binary is located at `python3.5` if you are using python version 3.5, or that your python was installed by homebrew. Is there any support for a different type of Python installation? I don't know of a professional Python developer that **doesn't** use virtual environments but I guess there must be some as I seem to be the first one reporting this issue.

- **OS and version used:** macOS 10.13.15

- **Python runtime used:** 3.5.5

Console output after running a modified [`build.sh`](https://github.com/Azure/azure-iot-sdk-python/blob/master/build_all/mac/build.sh). The modifications were mostly just setting the correct python executable and version numbers in the script, and also removing the last few lines that try to run the example code

```
~/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac ~/Desktop/azure-iot-sdk-python
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.5
-- Provisioning client OFF
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: x86_64
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libcurl'
--   Found libcurl, version 7.49.1
-- Found CURL: curl  
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
CMake Warning at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  /Users/matt/Desktop/azure-iot-sdk-python/device/iothub_client_python/CMakeLists.txt:42 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:1610 (message):
  No header defined for python35; skipping header check
Call Stack (most recent call first):
  /Users/matt/Desktop/azure-iot-sdk-python/device/iothub_client_python/CMakeLists.txt:42 (find_package)


-- Could NOT find Boost
CMake Error at /Users/matt/Desktop/azure-iot-sdk-python/device/iothub_client_python/CMakeLists.txt:44 (string):
  string sub-command REPLACE requires at least four arguments.


-- Found PythonLibs: /Users/matt/.pyenv/versions/3.5.4/lib/libpython3.5m.dylib (found suitable version "3.5.4", minimum required is "3.5") 
CMake Warning at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  /Users/matt/Desktop/azure-iot-sdk-python/service/CMakeLists.txt:42 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindBoost.cmake:1610 (message):
  No header defined for python35; skipping header check
Call Stack (most recent call first):
  /Users/matt/Desktop/azure-iot-sdk-python/service/CMakeLists.txt:42 (find_package)


-- Could NOT find Boost
CMake Error at /Users/matt/Desktop/azure-iot-sdk-python/service/CMakeLists.txt:44 (string):
  string sub-command REPLACE requires at least four arguments.


-- Configuring incomplete, errors occurred!
See also "/Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Test project /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac
No tests were found!!!
~/Desktop/azure-iot-sdk-python
copy iothub_client library to samples folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
copy iothub_client_mock library to tests folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/test/iothub_client_mock.dylib: No such file or directory
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client library to samples folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client_mock library to tests folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/tests/iothub_service_client_mock.dylib: No such file or directory
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
copy provisioning_device_client library to samples folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/src/provisioning_device_client.dylib: No such file or directory
copy provisioning_device_client_mock library to tests folder
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/tests/provisioning_device_client_mock.dylib: No such file or directory
cp: /Users/matt/Desktop/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/src/provisioning_device_client.dylib: No such file or directory
```

**Comment by pierreca** [comment] 2018-07-10 17:20
@mattdodge sorry to hear you're running into this; and thanks for filing the issue! We do have a lot of issues related to building on MacOS mainly because of our dependency on the boost library, which is what seems to be happening in your case too. We're trying to sort out what's happening with homebrew and why our installer can't find the library - or if it's because of a version difference or something.

To be completely honest, I'm a little short-handed right now, and being new to this area of the project I'm not sure how quickly I'll get you a solution - so I think I'm going to proceed in 2 steps: make it work once with a "golden configuration" sort of approach, then trying to support pyenv. If you find out anything else, please do let us know, and I'll keep updating this issue as I make progress.

**Comment by pierreca** [comment] 2018-07-13 02:12
@mattdodge tried a quick an dirty fix with #155 (well, I don't know if it's "dirty" but it works for me and needs to be better documented).

you'll need to check that you have the right dependencies installed using homebrew (openssl, cmake and boost-python) too.

Would you mind trying to pull these changes and let me know if this fixes it for you? i haven't tried to make it work with pyenv yet but I suspect this'll get you closer anyway.

**Comment by mattdodge** [comment] 2018-07-13 05:40
Ok, there's some progress now with that PR! Still not out of the woods yet but I think it's at least installed in the global Python environment at this point (small steps).

It didn't work right out of the box though, here are some things I found:

- I had to set some `BOOST_*` environment variables to make it happen, these did the trick for me:
```
export BOOST_ROOT=/usr/local/Cellar/boost/1.67.0_1
export BOOST_LIBRARYDIR=/usr/local/Cellar/boost-python3/1.67.0
```
- I also added this (appended) to the `cmake` command but not sure if it was needed or not
```-DBOOST_ROOT=$BOOST_ROOT -DBOOST_LIBRARYDIR=$BOOST_LIBRARYDIR```
- The latest version of `boost-python3` in Homebrew now is up to Python 3.7, so I was being greeted with errors like this:
```
-- Could NOT find Boost
Boost version: 1.67.0
Boost include path: /usr/local/Cellar/boost/1.67.0_1/include
Could not find the following Boost libraries:
        boost_python36
```
I forced the `boost-python3` install back to the 3.6 version like so
```bash
brew uninstall boost-python3
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6a77cdaac520f5d2f0a38f30606e91b7023ee5f0/Formula/boost-python3.rb
```
For future readers, you can see what version is installed by running this (you'll see `36` or `37` or maybe even just `3` in those filenames depending which version you have
```bash
ls -l /usr/local/Cellar/boost-python3/*/lib
```

Haven't tried it in the virtual environment yet, but I think this was step 1 to getting there. I'm almost certain I'm going to have to configure/boostrap boost manually in the virtualenv though. It might actually be easier than dealing with homebrew shenanigans but I didn't have much luck when I tried it earlier in the week.

**Comment by mattdodge** [comment] 2018-07-13 18:43
Ok, I'm getting really close with this. Here are some steps that I've run to make progres

1. Activate your virtualenv/pyenv
2. Download [boost source](https://www.boost.org/users/download/)
3. Edit the `tools/build/example/user-config.jam` file, make the last line look more like this. The key is to tell it to look in `python3.5m` if you are using python 3 or higher, not `python3.5`. Again, YMMV with this line
```
using python : 3.5 : /Users/matt/.pyenv/shims/python : /Users/matt/.pyenv/versions/3.5.4/include/python3.5m : /usr/lib ;
```
4. I still had to symlink `python3.5m` to `python3.5` in the `include` directory, couldn't figure out where boost was pointing to that
```bash
ln -s ~/.pyenv/versions/3.5.4/include/python3.5m ~/.pyenv/versions/3.5.4/include/python3.5
```
5. Install boost
```bash
./bootstrap.sh --with-python=`which python` --with-python-version=3.5 --with-python-root=`python-config --prefix`
./b2
```
6. Now, time to get the Azure SDK installed. Do **not** run the `setup.sh` script - that just installs boost which we've already done. I'm running a slightly modified `build.sh` from your branch @pierreca, basically with hard-coded Python directories. If I can actually get it to work I'll try to clean it up and make a PR

Right now I'm about 88% through the build process, it fails here:
```
[ 83%] Built target iothub_client_mqtt_transport
[ 83%] Built target prov_auth_client
[ 84%] Building C object provisioning_service_client/CMakeFiles/provisioning_service_client.dir/src/provisioning_service_client.c.o
[ 84%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_devicemethod.c.o
[ 85%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_devicetwin.c.o
[ 85%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_messaging.c.o
[ 86%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_messaging_ll.c.o
[ 86%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_registrymanager.c.o
[ 87%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_sc_version.c.o
[ 87%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/src/iothub_service_client_auth.c.o
[ 88%] Building C object iothub_service_client/CMakeFiles/iothub_service_client.dir/__/iothub_client/src/iothub_message.c.o
[ 88%] Linking C static library libprovisioning_service_client.a
[ 88%] Built target provisioning_service_client
[ 88%] Linking C static library libiothub_service_client.a
[ 88%] Built target iothub_service_client
make[1]: *** [python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/all] Error 2
make: *** [all] Error 2
```

One thing I've noticed though is that I keep encountering cmake cache issues. I've run `cmake` probably 1,000 times at this point with different combinations. @pierreca do you know of a way to "clean" the cache? I've been removing `CMakeCache.txt` files but that doesn't seem to clear it 100%.

These posts/questions/gists were helpful in me figuring this out, hopefully these steps can help someone else as well:
- https://stackoverflow.com/questions/8283603/boost-python-on-mac-os-x-lion-with-custom-python
- https://gist.github.com/melvincabatuan/a5a4a10b15ef31a5a481
- https://gist.github.com/alexlee-gk/ba07524dc0d972be9eac

**Comment by pierreca** [comment] 2018-07-13 18:58
@mattdodge I just pushed a script fix to enable support for python 3.7 (that you reported having issues with in your previous message). I'll go get help from the C SDK folks for your cmake question.

it looks like you're going to have to have a bootstrapped version of boost for each python version installed?

**Comment by mattdodge** [comment] 2018-07-13 19:01
Yeah, I think that would have to be the idea. I'm far from an expert on boost but it seems like the boost python wrappers are specific to the version of Python. A savvy user would probably put the build boost libraries inside the Python virtualenv's lib directory or something like that.

I do think it's only one boost per Python version though, not necessarily per virtual environment. I'll have to try it once I get a working version but it looks like two different virtualenvs built from the same python version should be able to share boost python libraries.

**Comment by pierreca** [comment] 2018-07-13 19:08
WRT to your cmake cache question, I have been told that deleting the cache file may not achieve what you want and that the best way to go about it is to remove the whole output folder that cmake creates (in my case it's in `<python-sdk-root>/c/cmake/iotsdk-mac` as defined line 6 in `build.sh`

**Comment by pierreca** [comment] 2018-08-16 03:31
@mattdodge I just released pip packages for MacOS, would you mind giving it a try?
```
pip install azure_iothub_device_client
```

it will still need to have boost installed, which you can deal with by doing:
```
brew install boost-python
```
or in the case of python3:
```
brew install boost-python3
```

Please do report if you're running into any sort of issue!

**Comment by mattdodge** [comment] 2018-08-27 18:45
Definitely some progress, it says it installs with pip but it's not quite working. It appears it is assuming you have python 3.7 when using pip to install. Notice here it tries to find a 37 boost library even though I'm in a 3.6 environment.

```shell
$ pip install azure_iothub_device_client
Collecting azure_iothub_device_client
  Using cached https://files.pythonhosted.org/packages/d1/7a/3e2beed9115f8163474eba23fe69aef757841dc9ffd6597f66203eacd1ad/azure_iothub_device_client-1.4.2-py3-none-macosx_10_6_x86_64.whl
Installing collected packages: azure-iothub-device-client
Successfully installed azure-iothub-device-client-1.4.2

$ python -c "from iothub_client import IoTHubClient"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/matt/.pyenv/versions/azure36/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: dlopen(/Users/matt/.pyenv/versions/azure36/lib/python3.6/site-packages/iothub_client/iothub_client.so, 2): Library not loaded: /usr/local/opt/boost-python3/lib/libboost_python37-mt.dylib
  Referenced from: /Users/matt/.pyenv/versions/azure36/lib/python3.6/site-packages/iothub_client/iothub_client.so
  Reason: image not found
```

I think I found the offending line here: https://github.com/Azure/azure-iot-sdk-python/commit/58784272dea2f6c8c1c2245923445e2bb3dd206d#diff-50dd46243f5d71c58448f491ace1cdf6R174
Is there any way to programmatically determine the Python version there rather than assuming 3.7?

I then tried to get my brew python up to 3.7 with a `brew upgrade python3` then `brew switch python3 3.7.0`. Did a reinstall with `pip` and got a seg fault
```shell
$ python -c "from iothub_client import IoTHubClient"
[1]    61316 segmentation fault  python -c "from iothub_client import IoTHubClient"
```

**Comment by harmv** [comment] 2018-10-26 14:15
With python 2.7 (on mac os) I have similar problems

```
$ python -V
Python 2.7.10

$ pip freeze
azure-iothub-device-client==1.4.3

$ python -c "from iothub_client import IoTHubClient"
Segmentation fault: 11
```

**Comment by pierreca** [comment] 2018-10-26 21:53
@harmv that is usually caused by not having curl installed from brew - there's a bug in the curl library that ships with MacOS by default. 
we support python 2.7 and 3.7 as installed by brew with boost-python, curl and openssl as dependencies. no other versions for now.

**Comment by pierreca** [comment] 2018-10-26 21:55
@mattdodge that's correct we assume a 3.7 environment. the problem we have when using boost is that we're stuck with a single version of python, boost, curl and openssl and all have to align. so we support what's published on brew and nothing else.

we're rewriting the SDK to get rid of this boost dependency. in the meantime, for our pip package, we're stuck with this single-version support nightmare :(

**Comment by jebrando** [comment] 2019-12-18 15:38
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK.  We will be closing the v1 SDK issues whose features are covered by the v2 release.  Feel free to open an new issue if you find an issue with the v2 SDK.

Thank you for your patronage

**Comment by az-iot-builder-01** [comment] 2019-12-18 15:38
@mattdodge, @harmv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by jebrando** 2019-12-18 15:38 UTC
Labels: boost, device-client, fixed-in-v2, macos, v1-deprecated
