### ISSUE TITLE
Upload to Blob example raises azure.core.exceptions.ServiceResponseError ('connection aborted.', timeout('...'))

### ISSUE THREAD

**Issue by dsilva-vd** [Azure/azure-iot-sdk-python#702] opened 2020-11-03 00:28 UTC
# Context

- **OS and version used:** 2020-02-13-raspbian-buster-lite (Linux)
- **Python version:** 3.7.3  
- **pip version:** 20.0.2 
- **list of installed packages:** 
azure-core            1.8.2    
azure-iot-device      2.3.0    
azure-storage-blob    12.5.0   
- **cloned repo:** upload_to_blob.py Git SHA 07b0f6ba3bbc005758d3b7d0a3c0598196f22a4d 

## Description of the issue
Using the upload_to_blob.py script (async example) 

Upload to blob fails over cellular connection with a file with size 791345 bytes (file is a compressed archive .tar.gz). A Service Exception is raised (see attached txt file)

Same file successfully uploads over Wifi

A smaller file (i.e. size 239641 bytes) successfully uploads over cellular connection

If there is a timeout regarding the Azure blob HTTPS API is there a way to set it using the python package? 

## Code sample exhibiting the issue

See attached .zip
[upload_to_blob.zip](https://github.com/Azure/azure-iot-sdk-python/files/5478671/upload_to_blob.zip)

## Console log of the issue

[Console.txt](https://github.com/Azure/azure-iot-sdk-python/files/5478670/Console.txt)

AB#8718086

**Comment by elhorton** [comment] 2020-11-09 20:45
Hi @dsilva-vd , thanks for the question, we'll look into this and get back to you shortly!

**Comment by cartertinney** [comment] 2021-01-15 18:40
We are attempting to reproduce the issue now. Are there any additional details you can share regarding your cellular connection to assist us in the matter?

**Comment by dsilva-vd** [comment] 2021-01-15 18:50
Hi Carter,

The only thing I can mention is the cellular connection was a LTE CAT1
modem with a UART connection to a host processor. The UART speed was set to
115200 kbps as this was the default speed.

As a test I increased the UART speed to 460800 and did not encounter this
issue. If the issue is related to an azure blob upload timeout can that
timeout be changed via an API?

Thanks

**Comment by danhellem** [comment] 2021-09-10 13:52
@cartertinney I will go ahead and investigate this and try and repo

**Comment by danhellem** [comment] 2021-09-16 15:53
@dsilva-vd I am not able to duplicate this issue on cell connection. As noted this is most likely caused by an upload timeout in azure storage. I am going to close this issue for now. If you are still experiencing this, and it is a priority, we can forward it over to the IoT Hub and Azure Storage teams to review.

**Closed by danhellem** 2021-09-16 15:53 UTC
Labels: bug, IoTSDK, needs-repro
