### ISSUE TITLE
Cannot run any requests on IoT Hub

### ISSUE THREAD

**Issue by DjinnTonic** [Azure/azure-iot-sdk-python#661] opened 2020-09-10 09:45 UTC
azure.iot.hub.IoTHubRegistryManager object gets created but any query run on it gives Bad Request error

`from azure.iot.hub import IoTHubRegistryManager`
`irm = IoTHubRegistryManager('connection-string')`
`irm.get_device('device-id')`

Anything even as simple as this returns:
HttpOperationError: Operation returned an invalid status code 'Bad Request'

Doesn't work from other people's machines, or with other IoT hubs either. It was all fine yesterday.

`irm.protocol.http_runtime.api_version` returns 2020-03-01, so it can't be that.

AB#8236271

**Comment by DjinnTonic** [comment] 2020-09-10 13:26
OK; so I installed the pre-release version 2.2.2rc0, which was released _yesterday_ (9 September) and the queries work only with the pre-release.
The api_version in the request URL is now 2020-09-30.

In my head this redefines the idea of "stable release"...

**Comment by Master-Matt** [comment] 2020-09-10 14:19
Just was about to create an issue. I ran `pip install azure-iot-hub --upgrade` and it is still broken

**Comment by elhorton** [comment] 2020-09-10 16:13
Hi @DjinnTonic and @Master-Matt , thanks for filing this issue. The latest pre-release API version is only available in a couple hub regions and is pre-release for testing purposes. @Master-Matt , when you run the pip install upgrade, this should fetch the stable 2.2.1 release, are you saying this is broken for you as well?

@DjinnTonic , wondering why you chose to upgrade to the pre-release package? Asking out of curiosity to understand you expectations around stable releases. When you roll back to 2.2.1 is it working for you?

**Comment by efra-mx** [comment] 2020-09-10 16:22
@elhorton I ran `pip install azure-iot-hub` and the issue is still there.

Everything works fine with `azure cli`, so it seems to be a python SDK issue

**Comment by mstiehm-NF** [comment] 2020-09-10 16:23
@elhorton, yes 2.2.1 is broken for me.

**Comment by Master-Matt** [comment] 2020-09-10 16:24
@elhorton, yes 2.2.1 is broken for me.

**Comment by DjinnTonic** [comment] 2020-09-10 16:30
> Hi @DjinnTonic and @Master-Matt , thanks for filing this issue. The latest pre-release API version is only available in a couple hub regions and is pre-release for testing purposes. @Master-Matt , when you run the pip install upgrade, this should fetch the stable 2.2.1 release, are you saying this is broken for you as well?
> 
> @DjinnTonic , wondering why you chose to upgrade to the pre-release package? Asking out of curiosity to understand your expectations around stable releases. When you roll back to 2.2.1 is it working for you?

No, 2.2.1 doesn't work. It only works with 2.2.2rc0. I tried that one because 2.2.1 was working fine yesterday, but when I ran it this morning it wasn't working any more, and I saw that there was a new release yesterday, so I had a hunch that it could work with that one. And it did. And digging into the formulation of the HTTP request, ,the only difference I could find was with the api_version in the URL.

**Comment by tonygleck** [comment] 2020-09-10 16:40
@DjinnTonic and @Master-Matt, we will give this a look and see what is happening.  Will let you know as soon as we get a handle on what's happening.

**Comment by jimbobbennett** [comment] 2020-09-10 16:55
I'm getting the same thing - it was working fine yesterday with 2.2.1, but today I get BadRequest with no changes to my code or IoT Hub. I'm using an IoT Hub hosted in WestUS2 that was created a while ago. Updating to 2.2.2rc0 fixes the issue.

**Comment by naiteeks** [comment] 2020-09-10 17:08
I have code samples that are being used by customers and as of today, this is the experience faced by everyone. Can we have this addressed asap?

**Comment by Master-Matt** [comment] 2020-09-10 17:12
@jimbobbennett, can confirm that updating to 2.2.2rc0 worked for me.

**Comment by elhorton** [comment] 2020-09-10 17:25
Hi all, an update on this issue. There are actually 2 separate concerns:

1) The priority issue is that the stable release-- 2.2.1-- is failing. This is because a version of the IoT hub, api version 2020-03-01, is down. We are working with the platform side to address this as it is outside the SDK's control. It is within our control to release a new package that moves to a stable api version. We will release this shortly. In the meantime, the workaround is to update to 2.2.2rc0.

2) The secondary concern is that the pre-release package, 2.2.2rc2, is using an api version that is not available in most regions and is preview for testing purposes. This is a known concern. *You should not upgrade to 2.2.2rc2*.

**Comment by avkewalr-msft** [comment] 2020-09-10 19:27
Hi, is there an ETA for this fix, our Ignite workplans are dependent on Python sdk working, this creates additional time to switch to c# SDK

**Comment by elhorton** [comment] 2020-09-10 21:10
Hi @avkewalr-msft , please see the above comment. To address the underlying IoT Hub issue, we are updating api version numbers in a release that should be out in a day or two. However, this is not an issue with the actual Python SDK so you shouldn't be concerned about needing to switch to another language. If you need to take immediate action, then bumping to 2.2.2rc0 is a good workaround.

**Comment by waitingkuo** [comment] 2020-09-11 03:54
How can I find the 2.2.2rc0 version? only saw the September 11 version but not September 9. Thanks!

**Comment by elhorton** [comment] 2020-09-11 04:16
Hi @waitingkuo , the recent 2.2.2 release fixes this issue and we recommend upgrading to that. If you'd like to see all versions of the azure-iot-hub package, you can see [this pypi page](https://pypi.org/project/azure-iot-hub/#history). The 2.2.2rc0 version is prerelease and not available in all regions, so we do not recommend upgrading right now. You can find that package [here](https://pypi.org/project/azure-iot-hub/2.2.2rc0/).

**Comment by elhorton** [comment] 2020-09-11 04:17
Closing this issue now as it has been resolved. Thanks everyone for raising and engaging with this.

**Comment by az-iot-builder-01** [comment] 2020-09-11 04:18
@DjinnTonic, @Master-Matt, @efra-mx, @jimbobbennett, @naiteeks, @avkewalr-msft, @waitingkuo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by elhorton** 2020-09-11 04:17 UTC
Labels: IoTSDK, bug

**Comment by naiteeks** [comment] 2020-09-11 19:07
I am seeing the following notification post upgrading to 2.2.2. Is this expected?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/42254991/92963445-4d89cd80-f427-11ea-9a7c-4db96176e23a.png)

**Comment by elhorton** [comment] 2020-09-11 19:37
hi @naiteeks , any more context for this warning? it doesn't appear to be associated with the azure-iothub package. Is any of your functionality broken?

**Comment by naiteeks** [comment] 2020-09-11 19:40
does not seem to break any functionality. But no idea why this message showed up after installing 2.2.2

**Comment by elhorton** [comment] 2020-09-11 19:46
I don't know either-- if this is a common problem that is breaking functionality, then we can open a separate issue. But for now I'd say this isn't a known concern. The warning appears to be associated with the azure-iot-toolkit
