### ISSUE TITLE
import iothub_client

### ISSUE THREAD

**Issue by Ilheu** [Azure/azure-iot-sdk-python#261] opened 2019-03-06 16:59 UTC
I'm trying to do this tutorial(https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload), in a Ubuntu 18.04 with python 3.6, and I keep getting this error message:

Traceback (most recent call last):
  File "FileUpload.py", line 3, in <module>
    import iothub_client
  File "/usr/local/lib/python3.6/dist-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by itslasya** [comment] 2019-03-20 09:53
Connection string={HostName=xxxx-xxxxx-iothub.azure-devices.net;DeviceId=xxxx7db9-5e17-43ca-9e97-e97ab969af68;x509=true}
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1412 x509 option has wrong value, the only acceptable one is "true"
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1463 iotHubName is not found
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:941 Failure creating iothub handle
Unexpected error IoTHubClient.IoTHubClient, IoTHubClientResult.ERROR from IoTHub

when ruuning

**Comment by pierreca** [comment] 2019-03-20 23:22
@itslasya i'm now moderating comments that are unrelated to the original issue. if you have an error message that is different from the original poster, there's no point in commenting everywhere. please file a new issue instead and follow the issue template.

@Ilheu The problem you're facing is related to the fact that you don't have libboost 1.58.0 installed on your system. It's a situation that a lot of folks run into because our SDK is tied to specific versions of python and boost that are from ubuntu 16.04 (and we're working on rewriting an SDK that does not have these limitations). the problem is explained here:
https://github.com/azure/azure-iot-sdk-python#important-installation-notes---dealing-with-importerror-issues

i'm closing this issue given this is a known limitation that has been addressed multiple times in other issues and in the readme.

**Comment by az-iot-builder-01** [comment] 2019-03-20 23:23
@Ilheu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-03-20 23:22 UTC
