### ISSUE TITLE
send_message with asyncio.wait_for

### ISSUE THREAD

**Issue by pbudel** [Azure/azure-iot-sdk-python#972] opened 2022-03-16 16:33 UTC
Hello, 

I am currently working on a piece of code using send_message and I have to manage the situation where connection is not available. Simply using send_message I see the code get stuck on send_message itself. I started using asyncio.wait_for together with it and I  can manage the situation as I want. However, I am getting "Task exception was never retrieved" message and I suspect there can be something I am not considering with the send_message. 

I saw this https://github.com/Azure/azure-iot-sdk-python/issues/775#issuecomment-852485494 and I'd like to know if you have been able to do some steps ahead in that direction. 

Thanks

**Comment by cartertinney** [comment] 2022-03-16 19:12
@pbudel

Which version of the package are you using?

**Comment by pbudel** [comment] 2022-03-16 20:27
@cartertinney 

~ # pip3 list|grep azure
azure-core          1.22.1   
azure-iot-device    2.10.0   
azure-storage-blob  12.9.0

**Comment by cartertinney** [comment] 2022-03-16 23:00
@pbudel

Okay, so in the latest version (which you have) the above linked issue has been addressed. What I suspect you're running into is that sending a message requires a connection. By default, the client will attempt to connect first (unless you specify that `auto_connect` is `False` at client creation), and I suspect that is causing the hanging.

As for `asyncio.wait_for()` let me take a look and see where we're at with that.

**Comment by pbudel** [comment] 2022-03-17 08:49
@cartertinney thanks. I will give you a bit more context on how I am testing this situation.

The **testing** environment where the code is running is an embedded system with 2 network interfaces: one is ethernet, the other one is Wi-Fi. The production HW will only have Wi-Fi and what I want to achieve is to be able to detect lack of connectivity (in production environment) to handle temporary buffering of the telemetry that will be then sent out once connectivity is back.

To reproduce the "production" situation what I am doing is:
1) connect the HW to the Wi-Fi that provides internet connectivity
2) connect the HW to my PC using ethernet port (no gateway settings. Just one to one connection). I use this connection simply to ssh into the linux system and play with it
3) once the SW is sending telemetry through the send_message I am shutting down the Wi-Fi connectivity (ifconfig wlan0 down)

Once the system boot up and connect the first time to the hub, there is no call to disconnect or shutdown so I am assuming the client should consider itself always connected. 

What happens when I am doing 3) is that send_message hung for a super long period (probably related to TCP timeout?). The use of `asynio.wait_for()` allows quick detection of the above mentioned situation but leads to "_Task exception was never retrieved_" that I don't like. This is why I am asking. 

**NOTE:** I understand testing environment is not reproducing perfectly the production environment, but I would expect that in this case fixing the code on test environment will make it even more robust on production

Hopefully you can have a better view of the situation or you have suggestion.
Thanks again

**Comment by cartertinney** [comment] 2022-03-17 23:10
@pbudel

I looked into it, and we are not able to support `asyncio.wait_for()` at this time as we cannot support task cancellation, which `asyncio.wait_for()` is dependent upon. We apologize for any inconvenience.

If you're looking for a way to detect a lack of connectivity, the `.on_connection_state_change` handler might be helpful. If you set a function on that property, it will be invoked every time the connection state changes. You can see what the connection state is by accessing the boolean property `.connected` on the client. Do note that depending on the `keep_alive` setting, a disconnection may take some time to be noticed.

I hope this helps. Let me know if there's any other assistance I can provide.

**Comment by pbudel** [comment] 2022-03-21 09:35
@cartertinney 

ok I got it. Given that `asyncio.wait_for()` is not supported I have changed approach. I think you could consider adding a timeout optional parameter on the `send_message` implementation. 

Now I am working only with the `.connected` boolean property and leaving `keep_alive` as default I see the disconnection in about 2 mins. It's far from the 3 seconds I was considering when trying `asyncio.wait_for()` but we can survive ;) 

Last question for you, once I am getting the disconnection I see the following:
```
Exception caught in background thread.  Unable to handle.
["azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Unexpected disconnection') caused by ConnectionDroppedError('Paho returned rc==1')\n"]
Exception caught in background thread.  Unable to handle.
["azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Unexpected disconnection')\n"]
```

Do you feel this is something expected? I am "obviously" (given the message) not able to catch `ConnectionDroppedError`.
Thanks

**Comment by cartertinney** [comment] 2022-03-21 18:14
@pbudel

Yeah, that looks like expected behavior when the internet connection is dropped while the client is trying to maintain a connection, which from what I understand is your use case. From the client's perspective, the connection going away is unexpected because no explicit connection ocurred.

Again, you can reduce the `keep_alive` to get the client to notice the connection drop faster.

I'll look into potential support for timeout, and discuss some options with our team, but I suspect we're going to run into the same issue as with `asyncio.wait_for()` in that supporting such a feature would require significant re-implementation.

**Comment by pbudel** [comment] 2022-03-24 10:18
@cartertinney 

Thank you. I am able to catch the exception and I will not change for `keep_alive` for now, I understand however your point.

Unfortunately it seems like I have another issue, probably related to the `http_pipeline` (not sure). On a task I am checking for file presence and eventually I am uploading it to an azure blob storage. If the disconnection happens when I am awaiting for `get_storage_info_for_blob()` to return... that task remains there indefinitely even if I am calling and explicit `disconnect()` once I got the dropped connection event from the telemetry. Is there any chance that the HTTP request will not be dropped/aborted by the `disconnect()` call? If not, wouldn't be a good idea to drop also that request?

**Comment by cartertinney** [comment] 2022-03-24 17:10
@pbudel

I'll take a look

**Comment by cartertinney** [comment] 2022-03-24 22:51
@pbudel

#980 adds some protection against the indefinite hanging, by timing out HTTP requests after 10 seconds. At this time explicit disconnect will not immediately cancel the task, it will just need the 10 seconds to timeout. We will continue to try and make some improvements in this domain in the future, alongside the initial request to improve the area around `asyncio.wait_for()`, but for now this should solve your immediate problem.

We will include this fix in the next release

**Comment by cartertinney** [comment] 2022-03-25 23:27
@pbudel 
#980 has been checked in. It will be included in the next release.

**Closed by cartertinney** 2022-03-25 23:27 UTC
Labels: question, investigation-required, IoTSDK

**Comment by pbudel** [comment] 2022-03-28 08:31
@cartertinney Thanks. I appreciate it.
