### ISSUE TITLE
Version mismatch in setup.py

### ISSUE THREAD

**Issue by c21415** [Azure/azure-iot-sdk-python#1100] opened 2023-02-08 22:24 UTC
# Context

- **OS and version used:** <python v3.10> (Buildroot)
- **Python version:** <v3.10> (in a command prompt: python --version )
- **pip version:** <not used> (in a command prompt: pip --version )
- **list of installed packages:** <VERSION> ( in a command prompt, from the directory containing your code: pip list )
- **cloned repo:** <2022-08-23> ( **If** you are using a cloned sdk repository, in a command prompt: git describe )

## The python setup.py mentions the "Programming Language :: Python :: 3.10" but requests-unixsocket>=0.1.5,<1.0.0 doesnt have a 3.10 version module

We are using the buildroot utils/scanpypi utility to create the azure-iot-device buildroot package

https://pypi.org/project/requests-unixsocket/

clone the buildroot and use the utils/scanpypi to create the buildroot pacakge then we get issues as dependant packages are not available with v3.10

**Comment by lev-i** [comment] 2023-02-09 21:33
@c21415 
To clarify, you're using scanpypi to create a buildroot package containing various PyPI modules (including requests-unixsocket)?

But the resulting buildroot package is unusable as the 0.1.5 version of requests-unixsocket is not compatible with Python 3.10?

**Comment by c21415** [comment] 2023-02-10 00:12
yes, that's correct. 

The requests-unixsocket and janus are not available for the python v3.10 and hence the scanpypi fails to create a pacakge for azure-iot-device

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/63671292/217967762-a833f83f-2ae0-4231-9081-9ec48cbc8edc.png">


<img width="1603" alt="image" src="https://user-images.githubusercontent.com/63671292/217967607-fd486301-f3cb-4221-8dc5-8437f18c2e89.png">


**When you mention python3.10 as a classifier in the setup.py, doesn't it mean all the required packages have python3.10 support?**

Would you be interested in pushing the auzre-iot-sdk pacakge as a standard package in the buildroot?

**Comment by cartertinney** [comment] 2023-02-10 00:29
@c21415 

I can confirm to you that requests-unixsocket does work on 3.10, as I run 3.10 as my primary development environment. I specifically use version 0.3.0, which meets the setup.py specification of >=0.1.5,<1.0.0. 

Same for janus, where I use the 1.0.0 release.

I'm not clear on what the issue is here, as these packages DO support 3.10. I'm not familiar with the buildroot/scanpypi tools you're using or why they think there's an error, but I can assure you that while they may be indicating an error, these packages do work in 3.10, as I use them every day while developing the SDK.

Could it be that potentially the tools are being thrown off by incorrect metadata on PyPI? requests-unixsocket for instance doesn't officially have the `Programming Language :: Python :: 3.10` classifier, but the lack of that classifier doesn't mean there isn't support for 3.10.

The only other thing I can think of to explain this would be something related to subdependencies (I see something in your error output about urllib which is a consistent issue for us re: versioning)? If you could give more information about the tooling, and what you're trying to do with it, and how it works, we might be able to try and resolve this, but ultimately, the package DOES support 3.10, it DOES install on 3.10, and whether or not this tool flags an error doesn't really affect that one way or the other.

**Comment by c21415** [comment] 2023-02-10 00:45
Thank you @cartertinney for the quick response.
The reason I suspect that requests-unixsocket package on pypi doesn't work on python3.10 is because it does not list python 3.100 as the programming language.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/63671292/217970681-c3209e44-163d-4a0b-829b-99f61e2aae21.png">

But I think I am wrong, as I am facing same error with janus but it has the python 3.10 as a listed programming language.  

Just to give a background on the buildroot, its a setup tool for building embedded linux images. When we need to build a kernel image for a linux target we can include various packages to be part of it. 
You can see that azure-iot-sdk-c is already part of it, https://github.com/buildroot/buildroot/tree/2022.11/package/azure-iot-sdk-c

May be you can clone the buildroot and use the utils/scanpypi to create a buildroot package. 

You can refer the scanpypi help to get more details on this tool.

**Comment by cartertinney** [comment] 2023-02-10 01:04
@c21415 How urgent is this concern for you? If you can't use this tool to include our package, do you have a workaround?

I ask because, right now I'm working hard at getting a version 3.0.0 of our SDK out, and that's where the majority of our development efforts are. This is certainly something we can look at supporting in a 3.0 release (especially since the janus dependency is being cut), but we're probably not looking to devote development time to getting this tool working on our 2.x releases unless it's a major blocking factor for you as a customer.

**Comment by c21415** [comment] 2023-02-10 01:14
We had a working demo on our buildroot setup with 'https://github.com/Azure/azure-iot-sdk-python' version/tag 'release_2019_01_03'
The older release mentioned above had the CMakeList based setup and it was working fine with python 2.x 

But now we are working on upgrading to latest buildroot and latest azure-iot-sdk-python but we hare having problems. 

What are the timelines for the 3.0.0 release? We are expecting it working by end of March. Let me know if you can provide support.

**Comment by c21415** [comment] 2023-02-10 02:19
Thank you, we have found a way to workaround installing the requests-unixsocket. Thank you for your support.

**Comment by lev-i** [comment] 2023-02-10 15:27
Marking as closed. Feel free to re-open or submit a new issue if there's anything else.

**Closed by lev-i** 2023-02-10 15:27 UTC
Labels: bug, IoTSDK
