### ISSUE TITLE
Python Upload Error - RRD

### ISSUE THREAD

**Issue by ToadTWP666** [Azure/azure-iot-sdk-python#160] opened 2018-07-17 13:24 UTC
- **OS and version used:** <Raspbian GNU/Linux 9 (stretch)> 

- **Python runtime used:** <2.7.13> 

- **SDK version used:** <Version that is found in the following link: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload> 

# Description of the issue:

I have built a number of Raspberry PI POC devices using the Python SDK code found on the following link: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload

This code has worked fine since Feb 2018 but in the last two weeks I have been getting the following error when I execute the program. What is interesting is that the upload reads through the files and  completes the uploads as Blobs to Azure storage. 

root@raspberrypi:/home/ImageProcessing# **python blobster.py**

Simulating a file upload using the Azure IoT Hub Device SDK for Python
    Protocol HTTP
    Connection string=XXXXXXXXXXXXXXXXXXXXXXXX

IoT Hub file upload sample, press Ctrl-C to exit
**Error: Time:Mon Jul 16 21:38:42 2018 File:/home/ImageProcessing/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Mon Jul 16 21:38:42 2018 File:/home/ImageProcessing/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating** iothub handle
testimage.jpg
testimage789.jpg
testimage456.jpg
...file uploaded successfully.
testimage345678.jpg
...file uploaded successfully.
testimage999.jpg

# Code sample exhibiting the issue:

import time
from time import sleep
import shutil
import sys
import iothub_client
import os
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult, IoTHubError

CONNECTION_STRING =""
PROTOCOL = IoTHubTransportProvider.HTTP

source = "/media/pi/images/"                                     # directory where raw images are stored
#dest1 =  "/media/pi/EMTEC C450/image_history/"                 # directory where archived images will be moved

def blob_upload_conf_callback(result, user_context):
    if str(result) == 'OK':
        print ( "...file uploaded successfully." )
    else:
        print ( "...file upload callback returned: " + str(result) )

def iothub_file_upload_sample_run():
    try:
        print ( "IoT Hub file upload sample, press Ctrl-C to exit" )
        client = IoTHubClient(CONNECTION_STRING, PROTOCOL)

        for root, dirs, filenames in os.walk(source):
            for f in filenames:
                FILENAME = f
                print(f)
                fullpath = os.path.join(source, f)
                f1 = open(fullpath, 'rb')
                content = f1.read()
                client.upload_blob_async(FILENAME, content, len(content), blob_upload_conf_callback, 0)
                f1.close()
                sleep(10)
                #shutil.move(source+f, dest1)  #Move all of the files into archive directory

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )
    except:
        print ( "generic error" )

if __name__ == '__main__':
    print ( "Simulating a file upload using the Azure IoT Hub Device SDK for Python" )
    print ( "    Protocol %s" % PROTOCOL )
    print ( "    Connection string=%s" % CONNECTION_STRING )

    iothub_file_upload_sample_run()
    exit()

# Console log of the issue:

**Comment by pierreca** [comment] 2018-07-17 17:41
@ToadTWP666 it looks like a duplicate of #158 - can you take a look? would you mind subscribing to #158 and closing this?

**Comment by pierreca** [comment] 2018-07-18 23:05
closing as duplicate, we're following up on #158.

**Comment by az-iot-builder-01** [comment] 2018-07-18 23:05
@ToadTWP666, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Closed by pierreca** 2018-07-18 23:05 UTC
Labels: investigation-required, raspbian
