### ISSUE TITLE
Using coroutines as iothub_client callbacks

### ISSUE THREAD

**Issue by DanielDiBe** [Azure/azure-iot-sdk-python#96] opened 2017-11-17 13:45 UTC
OS: Debian GNU/Linux 9.2 (stretch)
Python: 3.5.3
SDK client: '1.1.19.0'

# Description of the issue:
The SDK iothub_client does not accept setting a coroutine as a callback for set_device_method_callback.

Anything that gives me the ability to execute asynchronous code with the iot_hub client callbacks instead of forcing the device to return synchronously a value would work for me. For example the callback could have a callback function itself, or a Future, I could use to return the value instead of returning it via the return statement.

# Code sample exhibiting the issue:
```
import iothub_client
import asyncio

client = iothub_client.IoTHubClient("{connection string}", iothub_client.IoTHubTransportProvider.MQTT_WS)
client.set_device_method_callback(device_method_callback, 0)
async def device_method_callback(method_name, payload, user_context):
    print("Direct method:", method_name)
    return await asyncio.sleep(3, result=10)
```

# Console log of the issue:
**When calling a direct method to the device, the device code produces the following output because the call to the provided function creates a coroutine. The SDK does not try to execute the coroutine and undestands it as the result of the callback instead, which causes an error:**
TypeError: No registered converter was able to produce a C++ rvalue of type DeviceMethodReturnValue from this Python object of type coroutine

**Comment by zolvarga** [comment] 2017-12-11 20:40
@DanielDiBe 

I see your point and it is a valuable suggestion but we, provide the Python SDKs as a thin wrapper on top of the  C SDKs. 
We have not designed the Python SDK to resolve threading or other convenience needs.
Those implementations could be added by the user code on top of our APIs.

Best Regards,
Zoltan

**Comment by zolvarga** [comment] 2017-12-16 15:21
@DanielDiBe 

Closing as by design.

Best Regards,
Zoltan

**Closed by zolvarga** 2017-12-16 15:21 UTC
Labels: question

**Comment by khilscher** [comment] 2019-03-20 16:37
Also running into this issue, but not using coroutines/asyncio. Calling:

```
def device_method_callback(method_name, payload, user_context):
    print ( "\nMethod callback called with:\nmethodName = %s\npayload = %s" % (method_name, payload) )
    device_method_return_value = DeviceMethodReturnValue()
    device_method_return_value.response = "{ \"Response\": \"Executed direct method %s\" }" % method_name
    device_method_return_value.status = 200
    return 
```

Results in:
```
TypeError: No registered converter was able to produce a C++ rvalue of type DeviceMethodReturnValue from this Python object of type NoneType
```

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/debian_version
9.8
pi@raspberrypi:~ $ pip3 show azure-iothub-device-client
Name: azure-iothub-device-client
Version: 1.4.6
Summary: IoT Hub Device Client Library
Home-page: https://github.com/Azure/azure-iot-sdk-python/tree/master/device
Author: aziotclb
Author-email: aziotclb@microsoft.com
License: Apache Software License
Location: /home/pi/.local/lib/python3.5/site-packages
pi@raspberrypi:~ $ python3 --version
Python 3.5.3

**Comment by pierreca** [comment] 2019-03-20 23:26
@khilscher I believe you need to return the device_method_return_value that you are creating just before the return statement.

**Comment by khilscher** [comment] 2019-03-21 00:10
@pierreca Sorry, can't believe I missed that. Works now. Thanks.
