### ISSUE TITLE
receive_twin_desired_properties_patch on module - Get error message every 58 minutes

### ISSUE THREAD

**Issue by XUWeijiang** [Azure/azure-iot-sdk-python#647] opened 2020-08-19 07:35 UTC
# Context

- **OS and version used:** CentOS Linux 7 (Core)  Linux 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Python version:** 3.6
- **pip version:** 9.0.1
- **list of installed packages:** 
appdirs (1.4.4)
APScheduler (3.5.1)
asn1crypto (0.24.0)
azure-iot-device (2.1.4)
blinker (1.4)
certifi (2020.6.20)
cffi (1.14.0)
chardet (3.0.4)
click (7.1.2)
contextlib2 (0.6.0.post1)
cryptography (2.9.2)
cycler (0.10.0)
Cython (0.29.15)
datacontract3 (2.2.1)
decorator (4.4.2)
easydict (1.9)
et-xmlfile (1.0.1)
Flask (1.1.1)
Flask-Caching (1.7.2)
Flask-Cors (3.0.8)
Flask-Script (2.0.6)
gevent (1.4.0)
greenlet (0.4.16)
gunicorn (19.9.0)
idna (2.6)
imageio (2.8.0)
itsdangerous (1.1.0)
janus (0.4.0)
jdcal (1.4.1)
Jinja2 (2.11.2)
joblib (0.16.0)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.2.0)
linq3 (0.3.0)
Mako (1.1.3)
MarkupSafe (1.1.1)
matplotlib (3.2.0)
numpy (1.17.4)
onnx (1.6.0)
opencv-python (4.2.0.32)
openpyxl (3.0.3)
paho-mqtt (1.5.0)
pandas (1.0.1)
Pillow (6.1.0)
pip (9.0.1)
protobuf (3.12.2)
psutil (5.7.0)
py (1.9.0)
pycocotools (2.0.0)
pycparser (2.20)
pycrypto (2.6.1)
pycuda (2019.1.2)
pygobject (3.26.1)
pymongo (3.10.1)
pyparsing (2.4.7)
PySocks (1.7.1)
python-dateutil (2.7.5)
pytools (2020.3.1)
pytz (2018.9)
pyxdg (0.25)
PyYAML (5.3)
raven (5.26.0)
redis (3.4.1)
redislite (5.0.165407)
requests (2.22.0)
requests-unixsocket (0.2.0)
retry (0.9.2)
retrying (1.3.3)
scikit-learn (0.21.3)
scipy (1.5.1)
SecretStorage (2.3.1)
sentry-sdk (0.14.2)
setuptools (39.0.1)
six (1.15.0)
supervisor (4.2.0)
tensorrt (6.0.1.5)
torch (1.2.0)
torch2trt (0.1.0)
torchvision (0.4.0)
typing-extensions (3.7.4.2)
tzlocal (1.5.1)
urllib3 (1.25.9)
Werkzeug (1.0.1)
wheel (0.30.0)
x86cpu (0.4)
xlrd (1.2.0)
yacs (0.1.6)

## Description of the issue

I am listening desired property change in a separate thread as shown below. Everything works fine, and I can get every property change event. The problem is the code below prints error message every 58 minutes.

## Code sample exhibiting the issue
```python
from azure.iot.device import IoTHubModuleClient
import threading
import signal
import sys

module_client = IoTHubModuleClient.create_from_edge_environment()
twin = module_client.get_twin()    
print(twin)  

def twin_update_listener(client):
    print("Start listening to twin update.")
    while True:
        patch = client.receive_twin_desired_properties_patch()  # blocking call
        print("Twin desired properties patch received:")
        print(patch)


twin_update_listener_thread = threading.Thread(target=twin_update_listener, args=(module_client,))
twin_update_listener_thread.daemon = True
twin_update_listener_thread.start()
```

## Console log of the issue
The error message printed every 58 minutes is:

```
CoordinateRequestAndResponseStage(ResponseEvent): request_id 472d6e95-0c2c-49d9-9c7f-aa2352b61c45 not found in pending list.  Nothing to do.  Dropping
```

AB#8033797

**Comment by jebrando** [comment] 2020-08-19 18:51
@XUWeijiang Thank you for the Issue.  The message you're seeing is just a warning which should not effect your functionality, but we understand it's not an optimal situation.  We will investigate the issue to see why we are receiving this error message.

**Comment by BertKleewein** [comment] 2020-08-24 18:17
@XUWeijiang - this is a warning message that is safe to ignore.  We are lowering the severity from `warning` to `info` in commit #648.  

For more background, there are few factors in play:
1. The device library is communicating with IoTHub over MQTT v3, which supports usage where one side of the connection sends a PUBLISH packet and the other side responds with a PUBACK packet to indicate that the package has been received.  The PUBACK only indicated successful _delivery_.  It does not return any information about how the data in the packet was handled.
2. More specifically, IoTHub is using the MQTT QOS (quality of service) of 1.  This means that the protocol guarantees that a PUBLISH operation won't be successful unless it has been delivered _at least_ once.  With QOS 1, a packet might be delivered twice, and that's OK and expected.  If the side sending the PUBLISH doesn't receive a PUBACK, it will resend until it does.  As long as the other side returns at least one PUBACK, the PUBLISH is considered successful.
3. In order to support a request->response paradigm, the IoTHub communication uses a pattern where one side sends a packet with a well-formed topic that indicates a request and includes a request id ($rid).  When the other side responds, it sends a packet on a different well-formed topic which indicates a response and also includes the same request id.  The matching $rid values in the request topic and the response topic is used to match a request with it's corresponding response.
4. Because the library and IoTHub are using QOS=1, a given request might be sent twice, and the response might be returned twice.  Since the $rid values are unique, the upper layers are able to safely ignore the extra packets because those extra packets contain an $rid value which was already handled.
5. Every 58 minutes, the library needs to refresh its connection credentials (SAS token).  This causes the library to disconnect and reconnect to IoTHub.  Part of this reconnect involves sending a request to get the current device twin values, which causes a request->response operation as outlined above.
6. For reasons which require a deep understanding of our code, this request->response operation causes an extra response to be received when the request->response is caused by a credential renewal.  Since duplicate responses are already allowed because we're using QOS=1, this is not a serious issue.
7. The duplicate response manifests as this warning message.  Since this is an allowed and expected behavior, we've decided that it doesn't warrant a warning.

**Comment by elhorton** [comment] 2020-09-02 18:53
We've addressed this issue and are closing now.

**Comment by az-iot-builder-01** [comment] 2020-09-02 18:53
@XUWeijiang, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-09-02 18:53 UTC
Labels: IoTSDK, investigation-required
