### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by WeeDom** [Azure/azure-iot-sdk-python#102] opened 2017-11-24 11:40 UTC
I'm installing the sdk on a raspberry pi, raspbian 9.1 (stretch). Which is fairly irrelevant.

At step 6 of the readme.md section about moving the static object to the /devices folder, it would be really, really helpful if it was clearer that developers will also have to move the .so to their own directories in order to access it. I had to guess that for myself, and lost quite a bit of time before I did so.

Thanks
 @sergaz-msft asked me to log this, after we discussed it during a support transaction

**Comment by zolvarga** [comment] 2017-11-27 18:10
@WeeDom 

Please be more specific which documentation you are referring to.
I have checked this and it looks correct:
https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md

Best Regards,
Zoltan

**Comment by WeeDom** [comment] 2017-11-28 09:21
Hi,

Specifically, this section:

6. After a successful build, the iothub_client.so Python extension module is copied to the device/samples <https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples> and service/samples <https://github.com/Azure/azure-iot-sdk-python/blob/master/service/samples> folders. Visit these folders for instructions on how to run the samples.

It’s not clear that iothub_client.so needs to be copied to the directory a real app will be running in. My own scenario is that I wanted to create an app in ~/some-customer/src/python/customer-code.py. It took me too long to realise that your step 6. actually described something that I needed to do in order for my app to work.

By all means, if I’m wrong and there is a better way than copying the static object into my own app dir, then I’d be happy to hear it - but it’d be better for that also to be clearly documented.

Thanks
Dominic

**Comment by zolvarga** [comment] 2017-12-11 20:11
@WeeDom 

There are two ways how Python will find the binary modules needed.
1. The binary modules are downloaded to Python local store using PIP.
2. You copy the necessary binaries to the folder where you are running the Python application from.

Both ways are valid and correct. This is generic knowledge how to run Python, not specific to our SDKs. 

Best Regards,
Zoltan

**Comment by zolvarga** [comment] 2017-12-11 20:11
Closing as by design.

**Closed by zolvarga** 2017-12-11 20:11 UTC
