### ISSUE TITLE
File upload to blob storage  using IoT Hub failing at blob_upload_conf_callback(uploading to Blob storage)

### ISSUE THREAD

**Issue by KundhanSoothsayer** [Azure/azure-iot-sdk-python#247] opened 2018-12-24 18:38 UTC
- **OS and version used:** Windows 10
- **Python runtime used:**  Python 3.6
- **SDK version used:** azure-iothub-device-client 1.4.2

# Description of the issue:
We are using file upload functionality of IoT Hub, we are using IoT Device SDK Python to upload the files from Windows Virtual Machines.
The code to use http for file upload to IOTHub is failing with the following error.

```
Simulating a file upload using the Azure IoT Hub Device SDK for Python
    Protocol HTTP
IoT Hub file upload sample, press Ctrl-C to exit

File upload initiated...
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\httpapi_winhttp.c Func:HTTPAPI_CloneOption Line:1046 unknown option CURLOPT_VERBOSE
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\src\httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\blob.c Func:Blob_UploadBlock Line:109 HTTP status from storage does not indicate success (404)
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\blob.c Func:Blob_UploadMultipleBlocksFromSasUri Line:288 unable to Blob_UploadBlock. Returned value=0, httpStatus=1583020672
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step3 Line:721 HTTP code was 400
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:1024 IoTHubClient_LL_UploadToBlob_step3 failed
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:uploadingThread Line:2124 unable to IoTHubClientCore_LL_UploadToBlob
...file upload callback returned: ERROR
IoTHubClient sample stopped
generic error
```

As it relates to the first highlight, we believe the following is happening in this file,
https://github.com/Azure/azure-c-shared-utility/blob/1d622902d7842f94193fc394987f2b4e978bb700/adapters/httpapi_winhttp.c

In the function `HTTPAPI_SetOption`, the code is internally throwing `LogError("unknown option %s", optionName)` in line 1082 and the result variable in line 1081 is `HTTPAPI_INVALID_ARG`. 

We see in the file https://github.com/Azure/azure-c-shared-utility/blob/1d622902d7842f94193fc394987f2b4e978bb700/adapters/httpapi_curl.c

That in line 329 we see the option `CURLOPT_VERBOSE` being set

As it relates to the second highlight, this results in error at line 603 w.r.t code in https://github.com/Azure/azure-c-shared-utility/blob/1d622902d7842f94193fc394987f2b4e978bb700/src/httpapiex.c
```c
saveOptionResult =   HTTPAPI_CloneOption(optionName, value, &savedOption);

/*Codes_SRS_HTTPAPIEX_02_038: [If   HTTPAPI_CloneOption returns HTTPAPI_INVALID_ARG then HTTPAPIEX shall return   HTTPAPIEX_INVALID_ARG.] */
result = HTTPAPIEX_INVALID_ARG;
LOG_HTTAPIEX_ERROR();
```

# Code sample exhibiting the issue:

```python
import time
import sys
import iothub_client
import os
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult, IoTHubError
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue

PROTOCOL = IoTHubTransportProvider.HTTP

CONNECTION_STRING = "HostName=;DeviceId=;SharedAccessKey=”

PATHTOFILE = ""
FILENAME = ""

def blob_upload_conf_callback(result, user_context):
    if str(result) == 'OK':
        print ( "...file uploaded successfully." )
    else:
        print ( "...file upload callback returned: " + str(result) )
                                
def iothub_file_upload_sample_run():
    try:
        print ( "IoT Hub file upload sample, press Ctrl-C to exit" )

        client = IoTHubClient(CONNECTION_STRING, PROTOCOL)

        f = open(PATHTOFILE+FILENAME, "r")
        content = f.read()
        
        client.upload_blob_async(FILENAME, content, len(content), blob_upload_conf_callback, 0)
        f.close() 
        print ( "" )
        print ( "File upload initiated..." )

        while True:
            if not f.closed:
                f.close()
            time.sleep(30)
    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )
    
        print ( "generic error" )

if __name__ == '__main__':
    print ( "Simulating a file upload using the Azure IoT Hub Device SDK for Python" )
    print ( "    Protocol %s" % PROTOCOL )
    #print ( "    Connection string=%s" % CONNECTION_STRING )

    iothub_file_upload_sample_run()   
```

# Console log of the issue:
```
Simulating a file upload using the Azure IoT Hub Device SDK for Python
    Protocol HTTP
IoT Hub file upload sample, press Ctrl-C to exit

File upload initiated...
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\httpapi_winhttp.c Func:HTTPAPI_CloneOption Line:1046 unknown option CURLOPT_VERBOSE
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\src\httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\blob.c Func:Blob_UploadBlock Line:109 HTTP status from storage does not indicate success (404)
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\blob.c Func:Blob_UploadMultipleBlocksFromSasUri Line:288 unable to Blob_UploadBlock. Returned value=0, httpStatus=1583020672
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step3 Line:721 HTTP code was 400
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:1024 IoTHubClient_LL_UploadToBlob_step3 failed
Error: Time:Mon Dec 24 17:25:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:uploadingThread Line:2124 unable to IoTHubClientCore_LL_UploadToBlob
...file upload callback returned: ERROR
IoTHubClient sample stopped
generic error
```

[edit: @pierreca: 2019-1-18] formatting

**Comment by pierreca** [comment] 2019-01-18 19:55
@KundhanSoothsayer Thanks for filing this and sorry for the long response time. 
I'm not sure I understand if this happen 100% of the time or randomly?

@jspaith @massand A lot of this seem to happen within the bowels of the C SDK file upload code. not sure yet what the issue is but tagging you FYI.

**Comment by massand** [comment] 2019-01-18 21:12
@KundhanSoothsayer - is the repro on this issue in the C SDK seem familiar to you?
https://github.com/Azure/azure-iot-sdk-c/issues/757

If yes, we are investigating this Github issue and I recommend you subscribe to that bug for follow ups. Thanks!

**Comment by jebrando** [comment] 2020-01-02 19:32
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment] 2020-01-02 19:33
@KundhanSoothsayer, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-01-02 19:32 UTC
Labels: area-c-sdk, blocked, bug, v1-deprecated
