### ISSUE TITLE
Error showing from .iothub_client import *

### ISSUE THREAD

**Issue by kiran007francis** [Azure/azure-iot-sdk-python#205] opened 2018-09-25 10:28 UTC
Operating System: Windows 10
Language : Python
Version: Python 3.7

I was going through the tutorial given on Azure Portal's IoT Hub for sending telemetry. I am following the python tutorial https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-python .

![azure python tutorial](https://user-images.githubusercontent.com/43568831/46004833-7cd79080-c0d1-11e8-862c-26cbb7fe5017.PNG)

I followed the steps given exactly in the tutorial. The sample code to be executed was also given https://github.com/Azure-Samples/azure-iot-samples-python/archive/master.zip

When i run the **SimulatedDevice.py** in the folder **simulated-device** code i get the following error 

![error](https://user-images.githubusercontent.com/43568831/46004982-d93ab000-c0d1-11e8-8ba0-2db4b1351c5c.PNG)

I also tried the suggestions given on net. I created an anaconda environment in python 3.6 and python 2.7 . But the same error persists. Can someone help with the above issue?

**Comment by cfoisy-osisoft** [comment] 2018-09-25 12:39
I encounter the very same problem on Windows 10, anaconda 3.5.2

**Comment by kiran007francis** [comment] 2018-09-25 16:48
Do you have any solution?

**Comment by cfoisy-osisoft** [comment] 2018-09-25 18:00
Unfortunately no and I don't plan to investigate. I'll revisit once a fix is in.

**Comment by cfoisy-osisoft** [comment] 2018-09-25 21:08
I remember dealing with the boost-python part when I built from source a while ago. Our code has currently dependencies on Python 3.5.2 so I'll check if this can be relaxed, otherwise I'll wait for the boost-free version.

**Comment by jscott3201** [comment] 2018-10-02 17:07
Anyone on MacOS running into this issue: 

```
brew install openssl cmake boost-python
```

Fix the import error above running Python 2.7.15 when running the samples.

**Comment by matthewcarlisle** [comment] 2019-04-02 16:27
_"We're actively working on a new version of the SDK that doesn't depend on this external library and is written entirely in Python but it's going to take a few weeks to get out. I'd suggest using that specific version of anaconda until the new SDK is released."_

I've seen rumors of this new Python SDK and am wondering when it's going to be released.  Right now I'm in a situation where we want to use the Python SDK but Boost is a real pain (we had to compile it from scratch to hit our Python 3.4 dependency), and in addition some of the Provisioning Device SDK functions are not supported in Python, but are supported in the underlying C SDK (Symmetric Key attestation).  So we're looking at doing a mix of C SDK, Python SDK, Boost compilation.  Not optimal, and a pure Python implementation would be pretty amazing.

**Comment by pierreca** [comment] 2019-04-04 17:45
@matthewconners work is in progress over here:
https://github.com/azure/azure-iot-sdk-python-preview

Given it's preview work, it's not full-featured yet and there might be breaking changes but the MQTT-based version should be complete within the next few weeks.

**Comment by JoelBennett** [comment] 2019-05-08 20:06
For those of us not yet running the work-in-progress version, is there a workaround for installing/building boost to get around this?

**Comment by SalmaMamdouhSalem** [comment] 2019-08-08 13:16
Hello Everyone, Please I wanna to ask about if there is a solution, anyone finds it for the following error "import iothub-client error"????

Errors generated after running the sample are:
Traceback (most recent call last):
  File "SimulatedDevice.py", line 11, in <module>
    import iothub_client
  File "/home/pi/.local/lib/python2.7/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libboost_python-py27.so.1.62.0: cannot open shared object file: No such file or directory

**Comment by maranov** [comment] 2019-08-16 12:36
I'm having similar issues on Windows 10 & Python 3.5. The PYD module in the package has a dependency on the Python 3.6 DLL:

![dependency](https://user-images.githubusercontent.com/11609215/63167507-d4585500-c031-11e9-8dd2-432a708bc8b6.PNG)

The solution would be to instead provide 3.4, 3.5, 3.6, etc. .whl packages, build against corresponding Python interpreters (and Boost.Python respectively). The current `azure_iothub_device_client-1.4.6-py3-none-win32.whl` distribution on PyPi is incorrect – it should specify `py36-cp36-cp36m` instead of `py3-none`.

Until a proper multi-Python support is provided, the workaround is to simply build the SDK on your own, against the correct Python/Boost.Python.

**Comment by SalmaMamdouhSalem** [comment] 2019-08-18 08:26
Thanks alot for your fast response.
But I ran this azure example on raspbian OS not on windows 10, so If you use it please tell me how to solve this error?

**Comment by pierreca** [comment] 2019-08-29 01:16
@SalmaMamdouhSalem @maranov we're moving away from the boost-based SDK and have pushed our v2 to master: it should be much easier to install and use. as such, we won't be adressing the import error or new platform support based on v1, which we've moved to the v1-deprecated branch. Please give our new version a try!

**Comment by ilayn** [comment] 2019-08-29 08:04
If I am not mistaken this v2 breaks backwards compatibility even wn with the naming. So 3.6 is broken and 3.7 is a completely new API and still subject to change. Is this correct?

This hardly solves the original issue in my opinion.

**Comment by maranov** [comment] 2019-08-29 10:52
@pierreca, thanks. The new API looks promising, will probably upgrade once it's stable.

**Comment by pierreca** [comment] 2019-08-29 19:51
@ilayn that's correct. if we're going to rewrite the SDK, we might as well make the API pythonic instead of being a projection of the underlying C SDK. 

The v2 API at this point should be stable, and it is very well tested but given rubber is just meeting the road, we are keeping the preview tag on it for a few more weeks. 

what objects are you looking for?

**Comment by ilayn** [comment] 2019-08-31 15:55
I can't make it work on my Python 3.6.8 windows 10 machine. I get the same error with OP. The new SDK doesn't have the same objects importable from the same submodules.

**Comment by ilayn** [comment] 2019-08-31 16:05
Bah excuse my manners. What I actually meant is first that thanks for all the work that goes in for getting rid of Boost and other improvements. What I would like to stress is that if you can't make it work with the original SDK the new one is not a drop in replacement and you have to rewrite and rearrange your imports to use the new one. Essentially a complete rewrite in our case.

**Comment by SalmaMamdouhSalem** [comment] 2019-09-01 09:54
Please  @pierreca and @ilayn could anyone guide me from where I can find v2 that is mentioned above.

**Comment by SalmaMamdouhSalem** [comment] 2019-09-01 11:20
I want to add that I cloned the last pushed repository with the new updates but the problem is still exist and this error is still appeared "No module named  'iothub_client' "
Pleasee I ask for a quick response about this problem!

Notes:
I run the azure-python-sample on raspberry-Pi using raspbian OS and python v3.7.3 .

**Comment by ilayn** [comment] 2019-09-01 11:28
@SalmaMamdouhSalem Cloning won't solve the issue you also have to build it. Did you run `pip install azure-iot-device` ?

**Comment by SalmaMamdouhSalem** [comment] 2019-09-01 11:39
Yes, I ran this command >> pip install azure-iot-device.
**Sure,, This is my code..**
< 
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

import random
import time
import sys

# Using the Python Device SDK for IoT Hub:
#   https://github.com/Azure/azure-iot-sdk-python
# The sample connects to a device-specific MQTT endpoint on your IoT Hub.
import iothub_client
# pylint: disable=E0611
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue

# The device connection string to authenticate the device with your IoT hub.
# Using the Azure CLI:
# az iot hub device-identity show-connection-string --hub-name {YourIoTHubName} --device-id MyNodeDevice --output table
CONNECTION_STRING = "My-connection_String"

# Using the MQTT protocol.
PROTOCOL = IoTHubTransportProvider.MQTT
MESSAGE_TIMEOUT = 10000

# Define the JSON message to send to IoT Hub.
TEMPERATURE = 20.0
HUMIDITY = 60
MSG_TXT = "{\"temperature\": %.2f,\"humidity\": %.2f}"

def send_confirmation_callback(message, result, user_context):
    print ( "IoT Hub responded to message with status: %s" % (result) )

def iothub_client_init():
    # Create an IoT Hub client
    client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
    return client

def iothub_client_telemetry_sample_run():

    try:
        client = iothub_client_init()
        print ( "IoT Hub device sending periodic messages, press Ctrl-C to exit" )

        while True:
            # Build the message with simulated telemetry values.
            temperature = TEMPERATURE + (random.random() * 15)
            humidity = HUMIDITY + (random.random() * 20)
            msg_txt_formatted = MSG_TXT % (temperature, humidity)
            message = IoTHubMessage(msg_txt_formatted)

            # Add a custom application property to the message.
            # An IoT hub can filter on these properties without access to the message body.
            prop_map = message.properties()
            if temperature > 30:
              prop_map.add("temperatureAlert", "true")
            else:
              prop_map.add("temperatureAlert", "false")

            # Send the message.
            print( "Sending message: %s" % message.get_string() )
            client.send_event_async(message, send_confirmation_callback, None)
            time.sleep(1)

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )

if __name__ == '__main__':
    print ( "IoT Hub Quickstart #1 - Simulated device" )
    print ( "Press Ctrl-C to exit" )
    iothub_client_telemetry_sample_run()

>

**And this is a snap of the error after running this code.**

Python 3.7.3 (/usr/bin/python3)
>>> %cd /home/pi/python/azure-iot-samples-python-master/iot-hub/Quickstarts/simulated-device
>>> %Run SimulatedDevice.py
Traceback (most recent call last):
  File "/home/pi/python/azure-iot-samples-python-master/iot-hub/Quickstarts/simulated-device/SimulatedDevice.py", line 11, in <module>
    import iothub_client
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
    module = self._original_import(*args, **kw)
ModuleNotFoundError: No module named 'iothub_client'
>>>

**Comment by SalmaMamdouhSalem** [comment] 2019-09-02 07:21
@ilayn Please, There is any solution for my issue and a specific reason why it is happened? :)

**Comment by ilayn** [comment] 2019-09-02 08:22
Do you mind please editing your code and marking it as a copy pastable code? I can't run it as such. You can always look at the preview while editing.

**Comment by SalmaMamdouhSalem** [comment] 2019-09-02 08:40
```
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

import random
import time
import sys

# Using the Python Device SDK for IoT Hub:
#   https://github.com/Azure/azure-iot-sdk-python
# The sample connects to a device-specific MQTT endpoint on your IoT Hub.
import iothub_client
# pylint: disable=E0611
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue

# The device connection string to authenticate the device with your IoT hub.
# Using the Azure CLI:
# az iot hub device-identity show-connection-string --hub-name {YourIoTHubName} --device-id MyNodeDevice --output table
CONNECTION_STRING = "My-connection_String"

# Using the MQTT protocol.
PROTOCOL = IoTHubTransportProvider.MQTT
MESSAGE_TIMEOUT = 10000

# Define the JSON message to send to IoT Hub.
TEMPERATURE = 20.0
HUMIDITY = 60
MSG_TXT = "{\"temperature\": %.2f,\"humidity\": %.2f}"

def send_confirmation_callback(message, result, user_context):
    print ( "IoT Hub responded to message with status: %s" % (result) )

def iothub_client_init():
    # Create an IoT Hub client
    client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
    return client

def iothub_client_telemetry_sample_run():

    try:
        client = iothub_client_init()
        print ( "IoT Hub device sending periodic messages, press Ctrl-C to exit" )

        while True:
            # Build the message with simulated telemetry values.
            temperature = TEMPERATURE + (random.random() * 15)
            humidity = HUMIDITY + (random.random() * 20)
            msg_txt_formatted = MSG_TXT % (temperature, humidity)
            message = IoTHubMessage(msg_txt_formatted)

            # Add a custom application property to the message.
            # An IoT hub can filter on these properties without access to the message body.
            prop_map = message.properties()
            if temperature > 30:
              prop_map.add("temperatureAlert", "true")
            else:
              prop_map.add("temperatureAlert", "false")

            # Send the message.
            print( "Sending message: %s" % message.get_string() )
            client.send_event_async(message, send_confirmation_callback, None)
            time.sleep(1)

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )

if __name__ == '__main__':
    print ( "IoT Hub Quickstart #1 - Simulated device" )
    print ( "Press Ctrl-C to exit" )
    iothub_client_telemetry_sample_run()

```

**Comment by SalmaMamdouhSalem** [comment] 2019-09-02 08:42
Thank you for your quick response and sorry for the previous code, Now I write the right one, waiting for your response. :)

**Comment by jebrando** [comment] 2020-01-02 19:30
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment] 2020-01-02 19:30
@cfoisy-osisoft, @kiran007francis, @Petermarcu, @jscott3201, @matthewcarlisle, @JoelBennett, @SalmaMamdouhSalem, @maranov, @ilayn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2020-01-02 19:30 UTC
Labels: boost, question, v1-deprecated
