### ISSUE TITLE
Docker envirion

### ISSUE THREAD

**Issue by JohnathanLyu** [Azure/azure-iot-sdk-python#159] opened 2018-07-17 02:37 UTC
- **OS and version used:**  Ubuntu 16.04.1

- **Python runtime used:** Python 2.7.12

- **SDK version used:** azure-iothub-device-client-1.4.0

# Description of the issue:
------
I try the sample in a ubuntu docker container. Install python and necessary library.

When I run the code will show some error message. But it still go on. Then I check message is actually send out. I don't know why get the error message. Try to figure out and solve it .

# Code sample exhibiting the issue: 
------
I run [SimulatedDevice.py](https://github.com/Azure-Samples/azure-iot-samples-python/blob/master/iot-hub/Quickstarts/simulated-device/SimulatedDevice.py)

# Console log of the issue:
------
>Simulating a device using the Azure IoT Hub Device SDK for Python
    Protocol MQTT_WS
    Connection string=HostName=myhostname;DeviceId=mydeviceid
Error: Time:Tue Jul 17 10:19:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Tue Jul 17 10:19:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
IoT Hub device sending periodic messages, press Ctrl-C to exit
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
Send status: BUSY
Confirmation[0] received for message with result = OK
    message_id: message_0
    correlation_id: correlation_0
    Properties: {'Property': 'PropMsg_0'}
    Total calls confirmed: 1
^CIoTHubClient sample stopped

**Comment by pierreca** [comment] 2018-07-17 02:50
@JohnathanLyu Just to be clear, you're opening this issue because you're seeing this:
```
Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Tue Jul 17 10:19:41 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
```

correct?
could your issue be a duplicate of https://github.com/Azure/azure-iot-sdk-python/issues/158?

**Comment by JohnathanLyu** [comment] 2018-07-17 02:55
@pierreca  

Yes, sorry about this is duplicate of #158

**Comment by pierreca** [comment] 2018-07-17 03:03
@JohnathanLyu no problem at all - I'm closing this and suggesting you subscribe to #158. please let me know either there or here if the suggestion in #138 helps?

**Closed by pierreca** 2018-07-17 03:03 UTC
Labels: investigation-required, linux
