### ISSUE TITLE
Device to cloud messages V2.0.0 send_message issue

### ISSUE THREAD

**Issue by robbinvandamme** [Azure/azure-iot-sdk-python#441] opened 2020-01-20 08:24 UTC
I have some questions about the python azure client sdk (V2.0.0) and his send_message() call.
Protocol used is mqtt (default).

1. Should iot_hub_device_client.send_message() raise some kind of exception when it's not able to send the message due to no internet connection? According to the docs "help(IoTHubDeviceClient)" it should. But I'm not seeing that, it seems like its "stuck" forever on the "await iot_hub_device_client.send_message(msg)".  However, if the internet connection comes up again, the message goes trough. But I didn't expect that the sdk would wait forever on the "await iot_hub_device_client.send_message(msg)" until the connection comes up again.

2. Should iot_hub_device_client.send_message() raise some kind of exception when we try to send a message larger that 256k? When I do this, the call "await iot_hub_device_client.send_message(msg)" also hangs and I have no way get out of this state. If I cancel the task, who is sending the too large message, I'm not able to send any normal messages afterwards. I looks like the IoTHubDeviceClient is broken after send a too large request.

**Comment by robbinvandamme** [comment] 2020-01-20 16:38
I have the same kind of problem using the IoTHubDeviceClient.connect() call. 
When you create an IoTHubDeviceClient with an incorrect connection string and then call connect().
It keeps retrying, and it doesn't raise the exception stated in the documentation of the connect() call.

`async def init():
    # Connect IoTHubDeviceClient
    try:
        LOG.info("before connect" * 10)
        await iot_hub_device_client.connect()
    except Exception as exception:
        message = "%s: %s" % (type(exception).__name__, exception)
        LOG.info(message)
    await asyncio.sleep(1)
    asyncio.create_task(run2())
`

I'm I missing something here? Do I need the configure some retry policy?

[logs_invalid_connection_string.txt](https://github.com/Azure/azure-iot-sdk-python/files/4087099/logs_invalid_connection_string.txt)

**Comment by olivakar** [comment] 2020-01-21 19:41
For the first scenario, without an internet connection exception is raised as shown in the console/terminal below. But the connection is retried and so is sending the messages. This is the expected behavior. These IoT devices are used in many scenarios where connection is not consistent,  and we would like the ability to to retry sending the message after internet/connection comes back up.

```
ConnectOperation: completing with error None caused by [Errno 8] nodename nor servname provided, or not known
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [Errno 8] nodename nor servname provided, or not known.  Setting timer.
transport.connect raised error
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [Errno 8] nodename nor servname provided, or not known
```

For the third scenario, the output is still the above. But is there a reason or a scenario where you need to use an incorrect connection string ? It is difficult to distinguish between a no internet connection and a wrong connection string.

**Comment by BertKleewein** [comment] 2020-01-21 23:52
@robbinvandamme - You found 3 different bugs here and @olivakar and I are sorting through them and trying to figure out the next steps.  

For 1, the client is behaving correctly according to the way the code is written, but I don't think it's behaving the way users would expect.  What we have is a library that retries when the message fails to send.  We're missing a way for the library to give up at a certain point.  As written, it will keep retrying forever, and that's not what we want.  Our retry policy is very limited at this point, and it's not customizable (yet), but we need to figure out how to let users specify when to give up.

For 2, this is definitely a bug.  It's a bit tricky to fix, but it's definitely a bug.  Actually, it's 2 bugs: 1 bug is that the send_message call isn't failing and the second bug is that it's blocking all future send_message calls.  

For 3, can you be more specific about what you did to make an incorrect connection string?  I can imagine quite a few different ways to corrupt one and I just want to make sure I'm covering all my bases as we work through this.

**Comment by robbinvandamme** [comment] 2020-01-22 08:30
@BertKleewein glad to hear these bugs are being tackeled.

1. It would indeed be useful to let the users set a retry policy and if it fails to send the message within the policy, raise an exception towards the user. Now @olivakar says the exception is raised, and it might be raised in the sdk, but it's propagating towards the user who is calling "await iot_hub_device_client.send_message(msg)"? In my understanding, on this call, it hangs forever if connection doesn't come back. 
I might be able to work around this if the "is_connected()" call is available in V2.0.1? Before sending any messages I could check if the connection is up, and only then send messages.

2. True, this one was easy to work around by making sure our message size doesn't exceed 256KB.

3. I generated the connection string with an incorrect password (by accident) then you see that the sdk keeps retrying, even if it is impossible to make a connection to the IoTHub with the given connection string. I understand that once "connect()" gets called, the sdk keeps retrying to connect event if the connection drops for some time. But I think it should raise an exception towards the user if it is able to contact the IoTHub but not able to setup a due to a wrong password or unknown device-id?

**Comment by robbinvandamme** [comment] 2020-01-27 13:25
@BertKleewein is this something that will be fixed in the next release? Or when can we expect this?

**Comment by BertKleewein** [comment] 2020-01-28 20:45
@robbinvandamme - I don't have an ETA, but I am actively working on it.  

I'm able to reproduce your issues, but not exactly.  I can see from the log that you're using SymmetricKey auth.  When you say that you have an incorrect password. do you mean that you have in incorrect symmetric key?

When I try to repro, I get one of two behaviors:
1. If my symmetric key is completely invalid (not a base64-encoded string), then create_from_connection_string() raises an exception and I never get to call connect()
2. If my symmetric key is invalid, but still  a base64-encoded string, I get an auth error from connect()

In your case, you're getting an error from Paho: "Connection Refused: broker unavailable." which maps to "conenction failed" or "conenction dropped", which is being treated differently than an auth failure.  

The easy fix is to not retry if we get a "broker unavailable" error, but I"m nervous that I can't reproduce this.

What else could be different between your situation and mine?  Are you using a protocol gateway or some other sort of proxy?  What OS are you using?

**Comment by robbinvandamme** [comment] 2020-01-29 13:10
@BertKleewein I generated a wrong connection string (by accident), the **secret** in the example below was wrong. When I used the generated connection string to connect to the IoTHub, I got the logs attached above.
Connect() didn't raise an exception I could catch, if it did, I would know something was wrong with the connection string. In this case, it just keeps retrying, because the secret for this device didn't match the secret on the IoTHub. So I guess it would retry forever.

```
    device_id = f"{device_type}--{serial}"
    binary_secret = device_id.encode() + secret.encode()
    sas_token = base64.b64encode(binary_secret).decode('utf-8')
    conn_str = f"HostName={iothub_host};DeviceId={device_id};SharedAccessKey={sas_token}"
    LOG.info(conn_str)
    iot_hub_device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
    await iot_hub_device_client.connect()
```

**Comment by BertKleewein** [comment] 2020-02-19 18:43
The fix for this issue is currently in review: https://github.com/Azure/azure-iot-sdk-python/pull/460

**Comment by olivakar** [comment] 2020-02-28 19:09
There is a new release which should fail the connect in case of the above error.

**Comment by az-iot-builder-01** [comment] 2020-02-28 19:35
@robbinvandamme, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by az-iot-builder-01** 2020-02-28 19:35 UTC
Labels: bug

**Comment by kunalg06** [comment] 2020-08-10 09:28
hello im gettting similar issue, can you please help me here
![image_2020_08_10T08_53_50_798Z](https://user-images.githubusercontent.com/18356081/89768885-d99f9100-db19-11ea-8e06-97c55a0764fa.png)
![image_2020_08_10T08_29_40_465Z](https://user-images.githubusercontent.com/18356081/89768920-ede38e00-db19-11ea-9bac-5573d2ef4ca3.png)

@BertKleewein
