### ISSUE TITLE
[Technical Question]How do I handle azure.iot.device send_message hanging when message quota is exhausted

### ISSUE THREAD

**Issue by terryholland** [Azure/azure-iot-sdk-python#775] opened 2021-05-24 12:07 UTC
I have a project on raspberry pi that sends telemetry data to azure hub.  An issue I am coming up against is when I have exceeded by daily quota of messages being sent from my device to cloud, the following line hangs.

await client.send_message(message)

I am trying to get over this by using asyncio.wait_for, and setting a timeout of 2 secs, so that my code will not wait indefinitely to return from the send_message() method.

My code does timeout after the specified time, but I get another error that Im not sure how to deal with.

The code Im using is below...
==============================================================

```
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import Message
import time
import asyncio
from datetime import datetime

    
async def SendMessage(clientPairingId,clientDeviceId,type,subType,deviceState,pairingSetpoint=None):

        

    messageTemplate = """{{"iotDeviceId":"{iotDeviceId}","timeStampUTC":"{timeStampUTC}","clientPairingId":"{clientPairingId}","clientDeviceId":"{clientDeviceId}","type":"{type}","subType":"{subType}","state": "{deviceState}","setPoint": "{pairingSetpoint}"}}"""        
    connectionString="**********"
    client = IoTHubDeviceClient.create_from_connection_string(connectionString)
    
    await client.connect()
    
    message = Message(messageTemplate.format(iotDeviceId="xx1",
                                            clientPairingId=clientPairingId,
                                            clientDeviceId=clientDeviceId,
                                            type=type,
                                            subType=subType,
                                            deviceState=deviceState,
                                            pairingSetpoint=pairingSetpoint,
                                            timeStampUTC=datetime.utcnow()))
   

    
    
    await client.send_message(message)
    #await asyncio.sleep(300)
    await client.shutdown()

async def main():
    for i in range(1):
        try:
            coros=[SendMessage(clientPairingId="cp1",clientDeviceId="cd1",type="D",subType="ST1",deviceState="On",pairingSetpoint="n/a")]
            
            await asyncio.wait_for(asyncio.gather(*coros),.5)
            
        except asyncio.TimeoutError:
            print("Timed out")
        except asyncio.CancelledError:
            print("Cancelled")
        except Exception as e:
            print(e)
        except:
            print("catch all")

def handle_exception(loop, context):
    msg=context.get("exception",context["message"])
    
if __name__ == "__main__":
    s = time.perf_counter()
    #asyncio.run(main())
    asyncio.run(main(),debug=False)
    elapsed = time.perf_counter() - s
    print(f"{__file__} executed in {elapsed:0.2f} seconds.")
```
        
output
#################################################
Timed out
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ClientError('Unexpected failure')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
    return await self.future
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/CabinetFarming/WIP/POC_SimpleAzureSendMessageMock.py", line 30, in SendMessage
    await client.send_message(message)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/aio/patch_documentation.py", line 60, in send_message
    return await super(IoTHubDeviceClient_, self).send_message(message)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 301, in send_message
    await handle_result(callback)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 53, in handle_result
    raise exceptions.ClientError(message="Unexpected failure", cause=e)
azure.iot.device.exceptions.ClientError: ClientError('Unexpected failure') caused by CancelledError()
POC_SimpleAzureSendMessageMock.py executed in 0.51 seconds.

**Comment by cartertinney** [comment] 2021-05-24 18:34
@terryholland Which version of the azure-iot-device package are you using?

**Comment by terryholland** [comment] 2021-05-28 08:26
Sorry for delay.  Im fairly new to working within a raspbian environment (Im a windows developer).  Im not sure how to find the version of the package that I have installed.  If I try to install I get below

pi@raspberrypi:~ $ pip install azure.iot.device
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting azure.iot.device
  Downloading https://files.pythonhosted.org/packages/08/85/a5ae6090a935ac7bfc8bb2c02e4a09fa51ef7710d177cbf0c031c776b63a/azure_iot_device-2.6.0-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 915kB/s 
Requirement already satisfied: azure-iot-nspkg>=1.0.1; python_version < "3.0" in ./.local/lib/python2.7/site-packages (from azure.iot.device) (1.0.1)
Requirement already satisfied: requests-unixsocket<1.0.0,>=0.1.5 in ./.local/lib/python2.7/site-packages (from azure.iot.device) (0.2.0)
Requirement already satisfied: win-inet-pton; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from azure.iot.device) (1.1.0)
Requirement already satisfied: six<2.0.0,>=1.12.0 in /usr/lib/python2.7/dist-packages (from azure.iot.device) (1.12.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/lib/python2.7/dist-packages (from azure.iot.device) (2.21.0)
Requirement already satisfied: deprecation<3.0.0,>=2.1.0 in ./.local/lib/python2.7/site-packages (from azure.iot.device) (2.1.0)
Requirement already satisfied: paho-mqtt<2.0.0,>=1.4.0 in ./.local/lib/python2.7/site-packages (from azure.iot.device) (1.5.1)
Requirement already satisfied: PySocks in ./.local/lib/python2.7/site-packages (from azure.iot.device) (1.7.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.27,>1.21.1 in /usr/lib/python2.7/dist-packages (from azure.iot.device) (1.24.1)
Requirement already satisfied: futures; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from azure.iot.device) (3.3.0)
Requirement already satisfied: azure-nspkg>=3.0.0 in ./.local/lib/python2.7/site-packages (from azure-iot-nspkg>=1.0.1; python_version < "3.0"->azure.iot.device) (3.0.2)
Requirement already satisfied: packaging in ./.local/lib/python2.7/site-packages (from deprecation<3.0.0,>=2.1.0->azure.iot.device) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in ./.local/lib/python2.7/site-packages (from packaging->deprecation<3.0.0,>=2.1.0->azure.iot.device) (2.4.7)
Installing collected packages: azure.iot.device
Successfully installed azure.iot.device
pi@raspberrypi:~ $

**Comment by terryholland** [comment] 2021-06-01 08:29
Is there any update on this?

**Comment by cartertinney** [comment] 2021-06-01 22:04
@terryholland

For future reference, you can check your installed package versions with the "pip list" command. But I can tell from the output you have provided that you are now using 2.6.0

This is good news. 2.6.0 introduced a new feature that should hopefully solve your first problem - the hanging on .send_message(). When you instantiate the client, try using the `connection_retry=False` flag

e.g.
```python
client = IoTHubDeviceClient.create_from_connection_string(connectionString, connection_retry=False)
```

The issue you're running into is that when you exceed the quota, the IoTHub disconnects your device. The device then tries to reconnect, but as long as the quota has been exceeded, it will be rebuffed from the IoTHub. This is why it gets stuck - a loop of connecting, getting dropped, and then trying again. By turning off connection retry via the `connection_retry` parameter, you will be able to avoid this behavior. There will be no need to use asyncio.wait_for().

We are looking at trying to come up with a better solution specifically for the quota problem so that this doesn't happen in the first place, but we haven't been able to come up with a good solution yet.

We are also looking at solutions for addressing the issues when using `asyncio.wait_for()` but have nothing finished yet. However, in the meantime, by using the above suggestion, you should be able to avoid your problem entirely.

**Comment by tholland-cgf** [comment] 2021-06-02 10:00
Great - I will try your "connection_retry=False" suggestion this evening.  With regard to the asyncio.wait_for() issue, I was hoping that my code would be able to set a limit on how long to wait for my SendMessage code to return.  This is in case of any network issue causing a delay in making the connection.  I would not want to wait indefinitely as my application would need to be doing other stuff.

**Comment by cartertinney** [comment] 2021-06-02 16:58
@tholland-cgf 

We have a scheduled task to implement support for `asyncio.wait_for()`, but I don't have an exact timeline on when that will occur yet.

**Comment by tholland-cgf** [comment] 2021-06-02 21:29
Im afraid the connection_retry=False is failing for me.  I have done as you suggested and run pip list.  This does indeed return 
azure-iot-device    2.6.0

I simplified my test code to the following....

```
import time
import datetime

#from azure.iot.device.aio import IoTHubDeviceClient#, Message
from azure.iot.device import IoTHubDeviceClient,Message
import traceback

def sendMessages(n: int):
    iotDeviceId="GRPI01"
    conn_str="??"
    
    message = Message("test message")

    for i in range(n):
        print (i)
        try:
            # Create instance of the device client using the authentication provider
            device_client = IoTHubDeviceClient.create_from_connection_string(conn_str,connection_retry=False)
            #device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
            
            # Connect the device client.
            device_client.connect()
                

            print("{}\tSending message...".format(datetime.datetime.now()))
            device_client.send_message(message)
            print("{}\tMessage successfully sent!".format(datetime.datetime.now()))
            
            device_client.disconnect()
            
        except Exception as e:
            traceback.print_exc()
        

sendMessages(1)
    

```
   
When I run this I get the following exception

`Traceback (most recent call last):
  File "/home/pi/CabinetFarming/WIP/Test_SimpleSendMessageTest.py", line 18, in sendMessages
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str,connection_retry=False)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/patch_documentation.py", line 79, in create_from_connection_string
    connection_string, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/abstract_clients.py", line 230, in create_from_connection_string
    _validate_kwargs(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/abstract_clients.py", line 41, in _validate_kwargs
    raise TypeError("Unsupported keyword argument: '{}'".format(kwarg))
TypeError: Unsupported keyword argument: 'connection_retry'`


`device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)`
then my code does send.

If I look in file "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/abstract_clients.py" the _get_config_kwargs method only contains the following list of valid values
product_info
websockets
cipher
server_verification_cert
proxy_options
keep_alive


I guess Ive got something set up incorrectly?

**Comment by cartertinney** [comment] 2021-06-03 00:15
@tholland-cgf 

Something seems wrong with your environment - you may have 2.6.0 installed on some version of Python, but it doesn't seem like that is the version you are currently running that code on.

Try adding this snippet to your code and see what the output says.

```python
from azure.iot.device.constant import VERSION
print(VERSION)
```

**Comment by tholland-cgf** [comment] 2021-06-03 05:30
You are correct.  I get 2.5.0 output.  Is there a simple way for me to clean this up?  If not I can rebuild the raspberry pi and start again

**Comment by cartertinney** [comment] 2021-06-03 21:30
@tholland-cgf 

Without knowledge of your environment, I can't tell you exactly what's wrong or where - the issue is you need to find out which instance of Python is running your code, and install 2.6.0 of azure-iot-device on that version. If you can find the right version of python, the command to update would be

```
pip install --upgrade azure-iot-device
```

Otherwise, yeah, rebuilding it would probably work too, since that would install the latest version. But you probably want to avoid that if you can, and I would imagine it's probably just a good idea to get a handle on which python exactly you are running on your device.

**Comment by tholland-cgf** [comment] 2021-06-04 07:19
Ok.  It seems this comes down to my lack of experience of Python (I am a c# developer by day).

```
pi@raspberrypi:~ $ pip uninstall azure-iot-device
Uninstalling azure-iot-device-2.6.0:
  Would remove:
    /home/pi/.local/lib/python2.7/site-packages/azure/iot/device/*
    /home/pi/.local/lib/python2.7/site-packages/azure_iot_device-2.6.0.dist-info/*
Proceed (y/n)? 
```
I can see from this that v 2.6.0 is installed for python 2.7

```
pi@raspberrypi:~ $ pip3 uninstall azure-iot-device
Uninstalling azure-iot-device-2.5.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/azure/iot/device/*
    /usr/local/lib/python3.7/dist-packages/azure_iot_device-2.5.0.dist-info/*
Proceed (y/n)? y

```
and that v2.5.0 is installed for python 3.7

If I go ahead and try to remove from python 3.7, I get Permission Denied.  So I guess that this was installed using sudo pip3 install.

My application use should be using python 3.7.  I uninstalled both versions of azure-iot-device and then installed azure-iot-device using the command

`pip3 install azure-iot-device`

I am now able to use

`device_client = IoTHubDeviceClient.create_from_connection_string(conn_str,connection_retry=False)`


I need to get to grips with my python versions and pip and pip3.  I dont actually need python 2.7 but attempts to uninstall result in 

```
pi@raspberrypi:~ $ pip uninstall python
Not uninstalling python at /usr/lib/python2.7/lib-dynload, outside environment /usr
Can't uninstall 'Python'. No files were found to uninstall.
pi@raspberrypi:~ $ sudo pip uninstall python
Not uninstalling python at /usr/lib/python2.7/lib-dynload, outside environment /usr
Can't uninstall 'Python'. No files were found to uninstall.

```

I will do more reading on this.  Thanks for your help.  This has enabled me to progress

**Comment by tholland-cgf** [comment] 2021-06-04 07:29
As an update, I am trying to send 8000 messages in a simple loop so that I can get to the point of exhausting my quota (Im on free tier whilst developing).  By running the code above I get the following after around 750 iterations

```
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_base.SasTokenRenewalStage object at 0xb3b8c150>._run_op() call
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 103, in run_op
    self._run_op(op)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 203, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 302, in _run_op
    self._start_renewal_alarm()
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 203, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 371, in _start_renewal_alarm
    self._token_renewal_alarm.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

Should I be doing...

```
device_client = IoTHubDeviceClient.create_from_connection_string(conn_str,connection_retry=False)
device_client.connect()
device_client.send_message(message)
device_client.disconnect()
```
each time I send a message?  My device will be running 24/7 and in production messages would normally be sent approx every minute

**Comment by tholland-cgf** [comment] 2021-06-04 10:38
further update.  I have managed to exceed my daily quota.  If I now try to send a single message my code hangs.
After 5 mins there is still no response from the send_message statement.  This will kill my application unless I can set a time limit on this.  I was hoping to achieve this through use of asyncio.wait_for, but as you have mentioned, there is work to be done on this

![image](https://user-images.githubusercontent.com/82652798/120789251-4a8cbb00-c529-11eb-9847-a782ef9a4b80.png)

![image](https://user-images.githubusercontent.com/82652798/120789302-5ed0b800-c529-11eb-9847-ea02601a7fbd.png)

**Comment by cartertinney** [comment] 2021-06-07 23:36
@tholland-cgf 

My apologies, it seems there's been an oversight on my part - the new `connection_retry` feature alone isn't sufficient to fix this problem (as is). I'm going to work on a fix for you right away.

**Comment by terryholland** [comment] 2021-06-08 06:28
Much appreciated

**Comment by terryholland** [comment] 2021-06-14 19:27
you have a timescale of when you might be able to look at this @cartertinney ?

**Comment by cartertinney** [comment] 2021-06-14 19:39
@terryholland

I would expect it to be delivered this week. I have a fix implemented, just trying to make sure that it doesn't break anything else right now.

You can follow progress in #787 if you wish.

**Comment by terryholland** [comment] 2021-06-14 19:43
that's great.  Thanks

**Comment by cartertinney** [comment] 2021-06-17 18:06
@terryholland

I have a fix ready to go, however, depending on how you use the clients, you may find yourself running into another issue. Can you let me know more about your scenario?

* What kind of authentication are you using? Connection String? X509? Your own SAS tokens?
* Are you just sending data from your devices, or are you also receiving data?
* How long are you running your clients for?

**Comment by terryholland** [comment] 2021-06-18 07:32
I am currently connecting using connection_string though I will likely be changing that to X509 in abut 6 months.
Currently I am only sending data from device to cloud but I intend to be pushing data from cloud to device in the next 3 months
The clients run 24/7/365 sending messages ~every 15 mins

**Comment by cartertinney** [comment] 2021-06-18 18:01
@terryholland

Okay, so I'm going to push out a fix later today that will address your hanging issue. However, as mentioned there's another bug I uncovered while working on this, but I don't think it's going to present problems for you, so you should be fine, however I'm going to explain the situation anyway just so we're sure.

Currently, in order to keep a SAS based connection alive (i.e. using ConnectionString) a new authentication token gets generated every 58 minutes. Then the device will disconnect and immediately reconnect to the Hub with the new credentials. However, when the `connection_retry` is disabled as you are doing, this reconnection will not occur. Thankfully though, this shouldn't be an issue if you are only SENDING data, because we default the `auto_connect` feature to being enabled, and so you will automatically connect whenever you try to send (using those new credentials).

What I'm saying is, you may notice that a device goes offline for a few minutes between the credential being renewed and the next time you send a message, but you will have no problems actually sending any data. And I will be working to fix this issue as well next.

Any concerns about that?

**Comment by cartertinney** [comment] 2021-06-19 00:40
Version 2.7.1 has been released via PyPi containing the fix

**Comment by terryholland** [comment] 2021-06-19 08:34
@cartertinney I don't think this will be a problem for my in my use cases.  Thank you for the fix.  I will download today and test

**Comment by cartertinney** [comment] 2021-06-23 20:44
@terryholland

Following up, was this fix sufficient for your purposes?

**Comment by terryholland** [comment] 2021-06-23 21:04
I currently have some issue with my azure subscription and my services are disabled.  I am trying to resolve asap after which I will be able to test.  I will let you know as soon as I have done so

**Comment by terryholland** [comment] 2021-06-24 23:44
I just upgraded to azure-iot-device to 2.7.1.

with the following code

```
try:
        device_client = IoTHubDeviceClient.create_from_connection_string(iotHubConnectionString,connection_retry=False)
        device_client.connect()
        device_client.send_message(message)
        device_client.shutdown()
    except Exception as e:
        print(e)
```

my code no longer hangs and I get 

`OperationCancelled('Could not complete operation') caused by OperationCancelled('Operation cancelled before PUBACK received')`

This will do me for now.  Thank you

**Comment by terryholland** [comment] 2021-06-25 06:37
Update to the above.  Im now finding that I get a lot of exceptions in way before my I have exceeded my message quota 

![image](https://user-images.githubusercontent.com/10390177/123380673-a0341080-d587-11eb-9dd8-aa52db49e4ec.png)

The highlighted line comes from the except section in code sample

```
try:
        device_client = IoTHubDeviceClient.create_from_connection_string(iotHubConnectionString,connection_retry=False)
        device_client.connect()
        device_client.send_message(message)
        device_client.shutdown()
    except Exception as e:
        print(e)
```

FYI. This snippet is in a method that is called from multiple threads

**Comment by cartertinney** [comment] 2021-06-25 19:24
@terryholland I will look into why this may be occurring, but the best thing to do is avoid creating and shutting down clients in quick succession from multiple threads, as it can create a variety of issues (likely including this one).

Is it possible to create a single instance of the client that you maintain long-term, and merely use it to send a message when you need to, rather than creating a new one each time? And then only shutdown when you are truly done with the client? This is the preferred scenario that is most reliable.

**Comment by terryholland** [comment] 2021-06-26 05:41
I was previously using a singleton pattern.  I started having issues with this after the code fix so but I failed to note down the errors.  It was something like "Not Connected" when attempting to send_message.  I am guessing that this type of error would have been more likely since using the connection_retry=False parameter.  I will revert to my singleton pattern and make the code more robust so that it checks the state of the connection before attempting the send_message call.  I'll update this morning and let you know how it goes

**Comment by terryholland** [comment] 2021-06-26 06:34
something I have noticed since updating to 2.7.1 is the following

![image](https://user-images.githubusercontent.com/10390177/123504386-da1d1980-d650-11eb-8e9e-1415e37b64fb.png)

is this something you are aware of?

**Comment by terryholland** [comment] 2021-06-28 07:12
I have modified my code to use a singleton pattern for my with some handling for the device not being connected and all is working well

![image](https://user-images.githubusercontent.com/10390177/123595216-8f360a00-d7e8-11eb-8726-d110067c13dc.png)

**Comment by cartertinney** [comment] 2021-06-28 18:09
@terryholland

Wonderful, I'm glad to hear it. Thank you as well for pointing out the dependency issue, we will look into that as well.

Since things seem to be working for you now, I'm going to go ahead and close this issue. If you run into further issues, please feel free to open a new issue

**Closed by cartertinney** 2021-06-28 18:09 UTC
Labels: IoTSDK, fix-checked-in, investigation-required, question, waiting-on-reply

**Comment by terryholland** [comment] 2021-06-29 08:02
I left code running for 24 hours.  I seems I spoke too soon as I woke this am to see logs full of these errors:


2021-06-29 04:00:58,927	MAIN_GR	INFO:	T_Avg (Thread-2)	Reading	20.62466620889601
ReconnectStage: DisconnectEvent received while in unexpected state - LOGICALLY_DISCONNECTED, Connected: False
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 34, in handle_result
    return callback.wait_for_completion()
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
azure.iot.device.common.pipeline.pipeline_exceptions.OperationCancelled: OperationCancelled('Operation cancelled before PUBACK received')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/CabinetFarming/WIP/Pairings.py", line 80, in Start
    self._doWork(settings)
  File "/home/pi/CabinetFarming/WIP/Pairings.py", line 125, in _doWork
    pairingSetpoint=setPoint
  File "/home/pi/CabinetFarming/WIP/AZTelemetryService.py", line 66, in SendMessage
    self.client.send_message(message)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/patch_documentation.py", line 66, in send_message
    return super(IoTHubDeviceClient, self).send_message(message)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 322, in send_message
    handle_result(callback)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 56, in handle_result
    raise exceptions.OperationCancelled(message="Could not complete operation", cause=e)
azure.iot.device.exceptions.OperationCancelled: OperationCancelled('Could not complete operation') caused by OperationCancelled('Operation cancelled before PUBACK received')

**Comment by terryholland** [comment] 2021-06-29 08:08
This may be because Im calling this code from multiple threads.  I will try to lock the code and run again continuously.  I need this code to run 24/7 to I will keep test going for as long as possible
