### ISSUE TITLE
Client disconnects - and does not reconnect back , the caller of the thread does not connect back (though explicitly mentioned)

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [Azure/azure-iot-sdk-python#990] opened 2022-04-20 12:59 UTC
# Context

- **OS and version used:** Ubuntu 18.04
- **Python version:** Python 3.6.9.
- **pip version:** pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
- **list of installed packages:** 
azure-core==1.23.1
azure-iot-device==2.11.0
azure-storage-blob==12.9.0

## Description of the issue

Randomly I used to receive the below exception and it stucks there and client connectivity does not recover when I try to send message to IoTHub.

{/src/helpers/iothubOperations.py} 217] - Attempting to send message
Apr 20 01:01:49 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:49,072 W {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py} 130] - ReconnectStage: DisconnectEvent received while in unexpected state - DISCONNECTED, Connected: False
Apr 20 01:01:49 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:49,078 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 01:01:49 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:49,078 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
Apr 20 01:01:49 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:49,078 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 01:01:49 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:49,080 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
Apr 20 01:01:59 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:59,158 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 01:01:59 x86-000079 b8957f22f164[591]: [2022-04-20 01:01:59,158 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionFailedError\n']
Apr 20 01:02:19 x86-000079 b8957f22f164[591]: [2022-04-20 01:02:19,196 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 01:02:19 x86-000079 b8957f22f164[591]: [2022-04-20 01:02:19,196 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionFailedError\n']

I read in one of the issue (https://github.com/Azure/azure-iot-sdk-python/issues/399) the solution for this is to use connect explicit instead of using existing reconnect within SDK. - but the issue is still occurring with this error message

{/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,150 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,771 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,771 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.TlsExchangeAuthError\n']

## Code sample exhibiting the issue
from azure.iot.device.aio import IoTHubDeviceClient
##creating client
                self.client= IoTHubDeviceClient.create_from_connection_string(
                    self.cfg_model.conn_string, websockets=True)

    async def iothub_lib_send_message(self, message):
        success = False
        try:
            await self.client.connect()
            await self.client.send_message(message)

            success = True
        except Exception as e:
            LOG.debug(f"Failed with exception {e} while sending message to IOT hub")

        finally:
            return success

##caller to this as

                send_msg_loop = asyncio.new_event_loop()
                asyncio.set_event_loop(send_msg_loop)
                msg_send_status = send_msg_loop.run_until_complete(self.iothub_lib_send_message(message))
                send_msg_loop.close()

## Console log of the issue

{/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,150 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,771 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 28] - Exception caught in background thread.  Unable to handle.
Apr 20 09:29:44 x86-000079 b8957f22f164[591]: [2022-04-20 09:29:44,771 E {/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/handle_exceptions.py} 29] - ['azure.iot.device.common.transport_exceptions.TlsExchangeAuthError\n']

**Comment by pebneter** [comment] 2022-04-21 06:23
It sounds like this is the same problem as I have described here: https://stackoverflow.com/questions/71767695/azure-iot-device-loosing-connection-to-transparent-edge-gateway-device
What I have noticed on to of this: Once such a disconnect error occurs, the edgeHub become unresponsive to new connection attempts. In those cases I have to restart the edgeHub module to restore functionality.

**Comment by pebneter** [comment] 2022-04-21 07:10
I can supply some logfiles from the edgeHub module that might be useful:
A bit of context: around 06:58:50 the last successful message was sent. At 06:58:53 you see the next attempt and the failure.

```
<7> 2022-04-21 06:58:50.887 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] FLUSH
<7> 2022-04-21 06:58:50.887 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] FLUSH
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] RECEIVED: PubAckPacket[Type=PUBACK, QualityOfService=AtMostOnce, Duplicate=False, Retain=False]
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] RECEIVED_COMPLETE
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] READ
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x3ea18e0b, [::ffff:172.18.0.3]:48450 => [::ffff:40.113.176.174]:8883] READ
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager] - IotHub call succeeded
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Operation SendEventAsync succeeded for ipc28
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy] - Sending message for ipc28
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 1873 with batch size 100.
<7> 2022-04-21 06:58:50.941 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 1873.
<7> 2022-04-21 06:58:53.630 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] - Connection id ""0HMH3BH5EI5DU"" received FIN.
<7> 2022-04-21 06:58:53.630 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] - Connection id ""0HMH3BH5EI5DU"" sending FIN because: ""The client closed the connection.""
<7> 2022-04-21 06:58:53.630 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel] - Connection id ""0HMH3BH5EI5DU"" disconnecting.
<6> 2022-04-21 06:58:53.634 +00:00 [INF] [EdgeHub] - Closing connection for device: ipc35, ,
<6> 2022-04-21 06:58:53.635 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Disposing MessagingServiceClient for device Id ipc35 because of exception -
<6> 2022-04-21 06:58:53.635 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceProxy] - Setting device proxy inactive for device Id ipc35
<6> 2022-04-21 06:58:53.635 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager] - Removing device connection for device ipc35 with removeCloudConnection flag 'True'.
<7> 2022-04-21 06:58:53.636 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 => [::ffff:40.113.176.174]:8883] WRITE: DisconnectPacket[Type=DISCONNECT, QualityOfService=AtMostOnce, Duplicate=False, Retain=False]
<7> 2022-04-21 06:58:53.636 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 => [::ffff:40.113.176.174]:8883] FLUSH
<7> 2022-04-21 06:58:53.636 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 => [::ffff:40.113.176.174]:8883] CLOSE
<7> 2022-04-21 06:58:53.640 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient] - Received connection status changed callback with connection status Disabled and reason Client_Close for ipc35
<7> 2022-04-21 06:58:53.641 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 :> [::ffff:40.113.176.174]:8883] INACTIVE
<7> 2022-04-21 06:58:53.642 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 :> [::ffff:40.113.176.174]:8883] CLOSE
<7> 2022-04-21 06:58:53.642 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 :> [::ffff:40.113.176.174]:8883] UNREGISTERED
<7> 2022-04-21 06:58:53.643 +00:00 [DBG] [DotNetty.Handlers.Logging.LoggingHandler] - [id: 0x1912d048, [::ffff:172.18.0.3]:48446 :> [::ffff:40.113.176.174]:8883] HANDLER_REMOVED
``

**Comment by pebneter** [comment] 2022-04-21 14:29
I have made an observation that I think is key to this issue.
I used the sample script here that sends one single message: https://github.com/Azure/azure-iot-sdk-python/blob/main/azure-iot-device/samples/simple_send_message.py
I can execute the script 3 times successfully, and then it stops working.  Hence my conclusion that the edge Hub has an issue with closing connections gracefully (or the Python SDK does it not properly) and then the client script fails to re-connect.

@SURAJTHEGREAT can you try the same and see if you have the same effect?

By the way I also tested this with c-sharp sample scripts, and I can see the same issue there. So it may well be that the issue is in the edgeHub and not the Python SDK.

**Comment by SURAJTHEGREAT** [comment] 2022-04-21 17:06
@pebneter  - I have tried this similar code in my production env and received the random disconnects (the reason for the disconnect is not known) it does not happen regularly, hence the reason for raising the ticket.

However , I am also looking at other ways to send message to iothub using API  as in (https://docs.microsoft.com/en-us/rest/api/iothub/device/send-device-event) -but I am unable to send my enriched message ie (after adding custom property)
            message = Message(json.dumps(data))
            message.custom_properties["messageType"] = custom_property

and send this message something like this : 
requests.post(url, data=message, headers=headers, timeout=30)

**Comment by cartertinney** [comment] 2022-04-21 23:06
I think @pebneter is likely correct in his assessment on the cause. I'll reach out to Edge and see what we can do about this.

**Comment by SURAJTHEGREAT** [comment] 2022-04-22 06:25
@cartertinney  - Just to confirm that the issue I am facing is simple device python 3.6 code running on Linux and not an IoT Edge module running in a container.

**Comment by cartertinney** [comment] 2022-04-22 18:10
@SURAJTHEGREAT 

In that case, can you give me a more detailed log of your issue? You can do so by adding the following lines to your application:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

This will help me try and understand what's going on.

Additionally, with regard to why bypassing the client isn't working, it's because you are trying to send a Message object. If using requests, you would need to put the message payload as the `data` field of the request and then encode the custom properties in the header as indicated in the article you posted.

**Comment by cartertinney** [comment] 2022-04-22 18:26
@pebneter I'm trying to look into this that you mentioned here, but I'm a bit confused. You're using Edge you say, but the sample is not an Edge sample. Can you clarify this reproduction, and I will forward it to the Edge team?

> I have made an observation that I think is key to this issue. I used the sample script here that sends one single message: https://github.com/Azure/azure-iot-sdk-python/blob/main/azure-iot-device/samples/simple_send_message.py I can execute the script 3 times successfully, and then it stops working. Hence my conclusion that the edge Hub has an issue with closing connections gracefully (or the Python SDK does it not properly) and then the client script fails to re-connect.
> 
> @SURAJTHEGREAT can you try the same and see if you have the same effect?
> 
> By the way I also tested this with c-sharp sample scripts, and I can see the same issue there. So it may well be that the issue is in the edgeHub and not the Python SDK.

**Comment by SURAJTHEGREAT** [comment] 2022-04-23 02:40
@cartertinney - I have raised a ticket with MS Azure Team for the same is checked by an engineer and have shared logs with them for investigation. I am happy to share the logs with you as well on monday.Can we have a call for the same?

For the API , as per the documentation do I send my custom property with header as iotapp-hub-<myprop> and its value? and mypayload as string.

**Comment by pebneter** [comment] 2022-04-23 07:38
@cartertinney For clarification: I'm running the script on leaf devices and sending the data through a transparent edge gateway.

**Comment by cartertinney** [comment] 2022-04-28 22:50
@SURAJTHEGREAT

You would use the property `iothub-app-{your property name} header with some kind of string value to correspond, yes.

I believe I see an IcM that corresponds with your issue, although I don't see any logs there.

@pebneter 

Would you mind opening a new GitHub issue? It appears as though you are experiencing a different issue, and I'd like to separate the discussions. Please post any logs and information you have regarding how to reproduce, and then I can forward the information for the Edge team to look at.

**Comment by SURAJTHEGREAT** [comment] 2022-04-29 07:19
@cartertinney  -Thanks , sending property iothub-app-{your property name} header with string worked.
 Have shared the logs with sgeorge@microsoftsupport.com and assinha@microsoftsupport.com, it will be really great if you can speak with them to understand the issue and logs,

**Comment by pebneter** [comment] 2022-04-29 12:19
@cartertinney Ok, I will create a new issue and steps to reproduce.

**Comment by SURAJTHEGREAT** [comment] 2022-05-20 15:20
@cartertinney  - Is there any update on this

Since the SDK was throwing an unhandled exception – for the sake of business continuity we are streaming messages via the  REST API .

Ideally we are making this POST call every 10 seconds or so , which you might be aware is not the right approach.

Could you please suggest some alternative better approaches.?

**Comment by cartertinney** [comment] 2022-05-24 20:24
@SURAJTHEGREAT 

What is wrong about sending POSTs every 10 seconds?

**Comment by cartertinney** [comment] 2022-05-24 21:53
@SURAJTHEGREAT

In regards to the errors you're seeing when using the client, it seems that they are coming from a failure to verify certificates - is it possible that you are not using the correct CA certificate, or that your system certificate store is not correctly configured? Perhaps a certificate has expired? Based on the error you've been seeing, it seems the issue is with certificate validation.

Furthermore, a certificate problem (specifically around the system store) would make sense given that you aren't encountering HTTP problems, as many HTTP libraries handle certificates differently.

I have looked over your logs again, and they aren't showing the internal activity of the client because you haven't enabled client debug logging. As I mentioned in the past, I need you to add this piece of code at the beginning of your application in order to get logs containing useful information.

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by SURAJTHEGREAT** [comment] 2022-05-26 05:06
@cartertinney  - Answer to this question

_"What is wrong with sending POSTs every 10 seconds?"_ - Is it ok to overload IOTHUB  with a load of messages?
Also, I would like to understand internally how the SDK handles the request ? 

What are the steps that happen at the backend once I invoke SDK.send_streaming_data(msg)

For the query :

Probably the certificate has expired?  After making the logical change to send streaming via rest-API instead of SDK (the application is running without issues for past month without issue) why are we not seeing any issues related to certificates there?  

I can change it to as below to collect more logs after discussing with the customer
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by anthonyvercolano** [comment] 2022-06-08 14:40
@SURAJTHEGREAT -  My apologies for the delay.  Carter was suddenly called away out of country.  Should be returning quite shortly.

The Python SDK device side client does NOT generally ever use the HTTP protocol.  For telemetry/event operations it utilizes a protocol named MQTT.  If you desire, there is an OASIS spec for MQTT (3.1).  It's somewhat short reading.  MQTT is fairly pervasive in the IoT community.

Carter also asked: Do you happen to use PyInstaller?  There was a certificate bug associated with using this which could have influenced.

**Comment by cartertinney** [comment] 2022-06-08 18:59
@SURAJTHEGREAT 

Apologies for my delay in response, I am now back.

I think a few things need to be clarified:

1) The REST-based solution you have been using via HTTP IoTHub APIs in the meantime is not how our SDK works internally. As Tony mentioned above, our SDK operates over the MQTT protocol rather than HTTP, however the IoTHub has APIs for both.

2) It is not an issue to issue many requests to the IoTHub APIs. If you wish to continue using the HTTP REST solution, you should be able to use them as often as you like

3) It is very possible that an issue with certificates could only affect you when trying to use the SDK. This is because you are manually doing HTTP REST operations yourself, and your HTTP library may be using a different set of certificates.


Expanding on point 3, a likely reason the SDK may not be working for you is that you may not have your default Certification Authority (CA) certificates installed where we expect them to be. Our SDK uses OpenSSL, which should be included with your version of Ubuntu. Ensure that your certificates are located at `/usr/lib/ssl/certs` and if they are somewhere else (say, `/etc/ssl/certs` as an example that we've seen before), set up a symlink so that they will be located in the expected location.

You can read more about certificates on Ubuntu [here](https://ubuntu.com/server/docs/security-certificates) and more about how Python works with OpenSSL [here](https://docs.python.org/3/library/ssl.html)

**Comment by SURAJTHEGREAT** [comment] 2022-06-10 05:24
@cartertinney  - Thanks for the reply and detailed description. Much appreciated.

In the affected site, we could observe the certificates are available in the default location: ```/usr/lib/ssl/certs```  .Can you please provide me the exact certificate to look for in the location.

**Comment by SURAJTHEGREAT** [comment] 2022-06-20 07:16
@cartertinney  - Thanks for the reply .  We were not able to identify a specific pattern / exact circumstances under which this disconnect problem occurs. This is very random

Additionally for the logs (there are two logging syntax are introduced)

One logging syntax to look at the library logs. (commented as # to  see library logs)
And another logging syntax is application specific used to look at logs of our application.

Could you please review and let me know if this is the expectation.

![image](https://user-images.githubusercontent.com/9215832/174545135-69343813-2b30-4fbe-b9f3-26e6a7cf4c87.png)

Please let me know if I need to share the code base which does the iothub-related activities

**Comment by SURAJTHEGREAT** [comment] 2022-07-05 04:30
@cartertinney  - Yes the problem solves by shutting down the IoTHubDeviceClient and instantiating new one.
Additionally for the logs , I am waiting for approval from customer to make changes at their end.

**Comment by BertKleewein** [comment] 2022-07-25 22:07
@SURAJTHEGREAT - I think the TlsExchangeAuthError that's causing this needs to be treated as a retryable exception by the azure-iot-device library. I sent a workaround to sgeorge in the ICM that you can try.  I am leery to post the workaround in a public place until you can confirm that it resolves your issue.

**Comment by SURAJTHEGREAT** [comment] 2022-07-26 06:15
Thanks for the update @BertKleewein .

But could you please provide me some clarity under what scenario’s this function has be called ?

They can call this function at any time 
1.	Do I need to  call it every 30mins or  hourly once (like a cron scheduler)?
2.	Or look for a specific exception , catch it and then call the function?

How does this function address the issue?

**Closed** 2022-07-27 19:52 UTC
Labels: bug, investigation-required, IoTSDK, waiting-on-reply

**Comment by PeteDouma** [comment] 2022-11-18 17:32
I watch as my device got this and has been in this loop for days. 

`Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,191:azure.iot.device.common.pipeline.pipeline_stages_base:INFO:ReconnectStage(ConnectOperation): State changes LOGICALLY_DISCONNECTED->LOGICALLY_CONNECTED.  Adding to wait list and sending new connect op down:pipeline_stages_base.py:_run_op:956
Nov 17 16:00:11 gardyn GRD-SVC-IOT[5359]: 2022-11-17 16:00:11,196:root:INFO:calibration: 0x8333 (33587):ina219.py:_calibrate:282
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,211:azure.iot.device.common.mqtt_transport:INFO:Connect using port 8883 (TCP):mqtt_transport.py:connect:393
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,496:azure.iot.device.common.mqtt_transport:INFO:disconnected with result code: 7:mqtt_transport.py:on_disconnect:206
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,511:azure.iot.device.common.mqtt_transport:INFO:connected with result code: 0:mqtt_transport.py:on_connect:180
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,512:azure.iot.device.common.mqtt_transport:INFO:Forcing paho disconnect to prevent it from automatically reconnecting:mqtt_transport.py:_force_transport_disconnect_and_cleanup:297
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,522:azure.iot.device.common.pipeline.pipeline_stages_mqtt:INFO:_on_mqtt_connected called:pipeline_stages_mqtt.py:_on_mqtt_connected:325
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,527:azure.iot.device.common.pipeline.pipeline_stages_mqtt:INFO:MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('The connection was lost.'):pipeline_stages_mqtt.py:_on_mqtt_disconnected:372
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,541:azure.iot.device.iothub.abstract_clients:INFO:Connection State - Connected:abstract_clients.py:_on_connected:123
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,546:azure.iot.device.common.pipeline.pipeline_stages_mqtt:INFO:MQTTTransportStage: disconnection was unexpected:pipeline_stages_mqtt.py:_on_mqtt_disconnected:410
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,559:azure.iot.device.common.mqtt_transport:INFO:publishing on devices/f6c391f9-b8dc-4fea-92de-38d031b02a29/messages/events/:mqtt_transport.py:publish:548
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,552:azure.iot.device.iothub.abstract_clients:INFO:Connection State - Disconnected:abstract_clients.py:_on_disconnected:129
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,569:azure.iot.device.iothub.abstract_clients:INFO:Cleared all pending method requests due to disconnect:abstract_clients.py:_on_disconnected:133
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,561:azure.iot.device.common.handle_exceptions:INFO:Unexpected disconnection.  Safe to ignore since other stages will reconnect.:handle_exceptions.py:swallow_unraised_exception:52
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,584:azure.iot.device.common.handle_exceptions:INFO:azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The connection was lost.')
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: The above exception was the direct cause of the following exception:
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: Traceback (most recent call last):
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]:   File "/usr/local/lib/python3.9/dist-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]:     raise e
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('The connection was lost.')
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: :handle_exceptions.py:swallow_unraised_exception:53
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,598:azure.iot.device.common.mqtt_transport:INFO:Connect using port 8883 (TCP):mqtt_transport.py:connect:393
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,730:azure.iot.device.common.mqtt_transport:INFO:payload published for 1:mqtt_transport.py:on_publish:248
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,746:azure.iot.device.iothub.sync_clients:INFO:Successfully sent message to Hub:sync_clients.py:send_message:314
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,753:azure.iot.device.common.mqtt_transport:INFO:connected with result code: 0:mqtt_transport.py:on_connect:180
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,764:azure.iot.device.common.pipeline.pipeline_stages_mqtt:INFO:_on_mqtt_connected called:pipeline_stages_mqtt.py:_on_mqtt_connected:325
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,772:azure.iot.device.common.mqtt_transport:INFO:disconnected with result code: 7:mqtt_transport.py:on_disconnect:206
Nov 17 16:00:11 gardyn GRD-SVC-IOT_SERVER[535]: 2022-11-17 16:00:11,782:azure.iot.device.iothub.abstract_clients:INFO:Connection State - Connected:abstract_clients.py:_on_connected:123
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,800:azure.iot.device.common.mqtt_transport:INFO:Forcing paho disconnect to prevent it from automatically reconnecting:mqtt_transport.py:_force_transport_disconnect_and_cleanup:297
Nov 17 16:00:11 gardyn GRD-SVC-IOT[534]: 2022-11-17 16:00:11,808:azure.iot.device.common.pipeline.pipeline_stages_mqtt:INFO:MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('The connection was lost.'):pipeline_stages_mqtt.py:_on_mqtt_disconnected:372
Nov 1`

**Comment by davidroid** [comment] 2023-07-25 09:28
> Reference

Hello @SURAJTHEGREAT,
I'm experiencing the same disconnection issue; any reply/solution found in the meantime?

Thank you in advance.
Davide

**Comment by JP-WienEnergie** [comment] 2024-07-11 06:30
Hello @SURAJTHEGREAT, @davidroid  and @cartertinney,

I am experiencing the same disconnect issue:

` <WARNING> azure.iot.device.common.pipeline.pipeline_stages_base: ConnectionStateStage: DisconnectEvent received while in unexpected state - ConnectionState.DISCONNECTED
<WARNING> azure.iot.device.common.handle_exceptions: Exception caught in background thread. Unable to handle.
 <WARNING> azure.iot.device.common.handle_exceptions: ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']`
 
 using python3.8, azure-iot-device and azure-storage-blob. I have confirmed that the TlsExchangeAuthError fix is in my installed libs
 
 any updates on this topic?
