### ISSUE TITLE
IoTHubDeviceClient connect()/disconnect(): Exception when used in function. (Synch method)

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-iot-sdk-python#534] opened 2020-04-08 17:11 UTC
@HoLue commented on [Tue Apr 07 2020](https://github.com/Azure/azure-sdk-for-python/issues/10727)

- **Package Name**:  azure.iot.device
- **Package Version**:  ?
- **Operating System**: Windows 10
- **Python Version**:  3.7.4

**Describe the bug**
Unsing the synch method, a simple connect() and disconnect() of a device client (IoTHubDeviceClient) gives an error if it is done in a function. (Without the function ist works.) The exception message after about 10 seconds is:
Exception caught in background thread.  Unable to handle.
["AttributeError: 'NoneType' object has no attribute '_on_connected'\n"]

**To Reproduce**
Just run the following script with a valid connection string, the error occurs after about 10 seconds:

```
import os
from azure.iot.device import IoTHubDeviceClient
import time

def f():
    conn_str = 'YourConnectionString'
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
    # connect the client.
    device_client.connect()
    # usually do something but this dies not matter
    # Finally, disconnect
    device_client.disconnect()

# using the function
f()

# wait - after about 10 seconds the error occurs
for i in range(20):
    print(i)
    time.sleep(1)
 
```

**Expected behavior**
No exception (and therefore no exception message)

**Comment by olivakar** [comment] 2020-04-08 22:23
Is there a specific reason that you wish to do everything inside a function ?

I have figured out the root cause of the issue. While there is no immediate solution to the problem I can provide you a different way of doing if that is suitable in your scenario.

If possible please construct the client outside the function and let the function handle only connect and disconnect and other functionality like below :-

```
conn_str = "YourConnectionString"
device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)


def f():
    device_client.connect()
    # usually do something but this does not matter
    # Finally, disconnect
     device_client.disconnect()

# using the function
f()

# wait - after about 10 seconds the error occurs
for i in range(20):
    print(i)
    time.sleep(1)
```

**Comment by HoLue** [comment] 2020-04-09 05:21
Well, this works. But may I ask what is done in the background? There seems to be some connection? Data transfer?

**Comment by olivakar** [comment] 2020-04-09 18:53
If you are referring to the error that you received, that is simply a handler that lets you know that the you are connected. 

Please close the issue if this has helped you.

**Comment by HoLue** [comment] 2020-04-14 05:44
I cannot close, can I? (lmazuel opened this issue 6 days ago)

**Comment by olivakar** [comment] 2020-04-14 07:14
ok we will close

**Comment by az-iot-builder-01** [comment] 2020-04-14 07:15
@lmazuel, @HoLue, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by az-iot-builder-01** 2020-04-14 07:15 UTC
Labels: IoTSDK, device-client
