### ISSUE TITLE
Create device without generating keys

### ISSUE THREAD

**Issue by emft** [Azure/azure-iot-sdk-python#107] opened 2017-12-08 23:40 UTC
- **OS and version used:** Windows 10

- **Python runtime used:** Python 3.6.3

- **SDK version used:** azure-iothub-service-client-1.1.0.20

### Description of the issue:
Right now, creating a new device via the Python Service SDK requires passing primary key and secondary key parameters.  But these parameters are not required in the REST API, the Node.js SDK, or the IoTHub UI (if they are not provided they are auto-generated).  This should also be possible in the Python SDK.

### Code sample exhibiting the issue:
```
manager = iothub_service_client.IoTHubRegistryManager(CONNECTION_STRING)
auth_method = iothub_service_client.IoTHubRegistryManagerAuthMethod.SHARED_PRIVATE_KEY
manager.create_device(DEVICE_ID, None, None, auth_method)
```
Not passing arguments aside from `DEVICE_ID` fails similarly.

### Console log of the issue:
```
Traceback (most recent call last):
  File "C:\Users\emft\AppData\Local\Continuum\miniconda3\envs\iothub\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-dbe7b058fa33>", line 1, in <module>
    device = manager.create_device(DEVICE_ID, None, None, auth_method)
Boost.Python.ArgumentError: Python argument types in
    IoTHubRegistryManager.create_device(IoTHubRegistryManager, str, NoneType, NoneType, IoTHubRegistryManagerAuthMethod)
did not match C++ signature:
    create_device(class IoTHubRegistryManager {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, enum IOTHUB_REGISTRYMANAGER_AUTH_METHOD_TAG)
```

**Comment by zolvarga** [comment] 2017-12-11 19:15
@emft 

Use empty string for primary and secondary keys. ("").
I agree the None should do the same, I made a note about it.

Best Regards,
Zoltan

**Comment by emft** [comment] 2017-12-11 19:31
@zolvarga thanks for letting me know.  Is this documented somewhere?

**Comment by zolvarga** [comment] 2017-12-11 20:01
Closing it as by design.

**Closed by zolvarga** 2017-12-11 20:01 UTC
