### ISSUE TITLE
Connection failures while sending messages to Azure IoT Hub using Python SDK

### ISSUE THREAD

**Issue by pvvpraveen** [Azure/azure-iot-sdk-python#698] opened 2020-10-23 20:30 UTC
# Context
This issue is raised in below forum as well.
https://docs.microsoft.com/en-us/answers/questions/132626/azure-iothub-python-sdk-connectionfailederror-whil.html

- **OS and version used:** Windows 10, Raspberry Operating System(3b+,4b models)
- **Python version:** Python 3.7
- **pip version:** 20.2
- **list of installed packages:** azure-iot-device==2.3.0 ;  azure-iot-hub==2.2.3
- **cloned repo:** NA
 
## Description of the issue

While sending messages to Azure IoTHub from Python SDK,  the connection is frequently getting lost with different error messages :
1)Failed to receive on socket :
2)Transport.connect raised error
Also, some times IoTHub is receiving multiple(duplicate) messages for the same request.

## Code sample exhibiting the issue

Attached the sample code.
[IotHubClient_PythonSDK.txt](https://github.com/Azure/azure-iot-sdk-python/files/5431630/IotHubClient_PythonSDK.txt)

## Console log of the issue

Attached the error screenshot.
![IoTHub connection error](https://user-images.githubusercontent.com/24903340/97050964-97b1b300-157e-11eb-8c41-40b41fe06cfd.JPG)

AB#8654767

**Comment by elhorton** [comment] 2020-10-26 17:50
Hi @pvvpraveen , thanks for reaching out! From our experience, this looks like an issue with the IoT Hub service rather than the SDK. We could check logs to validate if you provide a timeframe and IoT Hub name, but this shouldn't be shared publicly and is best done by [opening a support ticket](https://docs.microsoft.com/en-us/azure/iot-fundamentals/iot-support-help) through Azure portal with any Azure subscription. Could you file a ticket? Let us know if you have issues with this, we can find a way to troubleshoot this issue by getting your info privately.

**Comment by elhorton** [comment] 2020-11-02 17:17
Hi @pvvpraveen , was this resolved for you? Were you able to open a support ticket to further investigate? If all is good, we will close this issue-- please let us know if you have any other updates or feedback for the Python SDK.

**Comment by pvvpraveen** [comment] 2020-11-02 17:34
Hi elhorton,

I have raised a ticket and they are still investigating it. The issue may not be with IoT Hub , as it is working fine with C# SDK.

**Comment by olivakar** [comment] 2020-11-02 17:42
I know you have shared the hub name in ur service ticket, but it would great if you can share your full connection string in the service ticket.  __Please don't share it here.__

Also please report the time frame and the day on which you faced these issues for python SDK. Like a to and from date/time frame.

Also are you using the exact same hub and exact same device for both the python and C# SDK ?

**Comment by pvvpraveen** [comment] 2020-11-02 17:50
Sure, will do.
Yes, I have been using the same kind of device(Raspberry Pi 3b model) for both the SDKs. The issue can also be reproduced from a Windows 10 computer.  Please note that the frequency of the connection failures increases when we send more than 100 kb file.
There is a mail chain going on with the support team where I shared all the details and logs(with timestamps,etc).

**Comment by pvvpraveen** [comment] 2020-11-02 18:33
Yes, in the sample we are reading only one static file and send it to the IoT Hub for every 40 seconds. 
In reality, we read a dynamic file and the loop runs till the scheduler(cron job) is stopped.
Should I attach the file in the service ticket or in the email?

**Comment by olivakar** [comment] 2020-11-02 19:04
yes please..the file that you referred to as being larger in size....

**Comment by pvvpraveen** [comment] 2020-11-02 19:20
Sent it in the mail, please check.

**Comment by olivakar** [comment] 2020-11-02 19:41
can you attach it to the service ticket ? if you have sent to my gmail , I still don't see it.

**Comment by pvvpraveen** [comment] 2020-11-02 20:07
I sent it to support@mail.support.microsoft.com, now attached to the ticket as well.

**Comment by olivakar** [comment] 2020-11-02 23:14
I still see the `output.zip` and the `IotHubClient_PythonSDK.txt` file on your ticket.
But I do not see any third attachment for mp3.

Also another question 

Also are you using the exact same hub and exact same device for both the python and C# SDK ? I meant did you use the same connection string for both of your devices for the C# and Python.

**Comment by pvvpraveen** [comment] 2020-11-03 09:39
Hi, I can see that in the ticket.
![image](https://user-images.githubusercontent.com/24903340/97969594-8eb3b380-1dc0-11eb-9947-becf8d407eb8.png)

Yes, we have used same device and connection strings for python(on Raspbian OS) and C#(Windows IoT core OS)) sdks.

**Comment by olivakar** [comment] 2020-11-03 20:39
okay i got the files.
How long did you run your sample in the windows 10 computer before you saw the error ?

**Comment by playboxsthlm** [comment] 2020-11-05 09:19
Ranging from 2 mins to 30 mins. We either get connection failed error or duplicate messages. 
Are you able to reproduce this?

**Comment by pvvpraveen** [comment] 2020-11-05 09:26
Ranging from 2 mins to 30 mins. Screenshot attached under the section "Console log of the issue"  shows that it failed after sending just 2 messages.
We either get connection failed error or duplicate messages.

Are you able to reproduce this?

**Comment by olivakar** [comment] 2020-11-05 22:17
So with the file that you had attached , I could actually run your sample for 2 days continuously without ever encountering the issue.  Are you encountering this issue even today ?

**Comment by asergaz** [comment] 2020-11-09 11:01
@pvvpraveen let us know if you are still encountering the issue at the moment? Thanks

**Comment by olivakar** [comment] 2020-11-09 18:38
By any chance is there any other audio file that you had sent other than the one you attached in the service ticket ?
If so please also attach those if you are still seeing this error.

**Comment by playboxsthlm** [comment] 2020-11-09 20:43
Hello,

The issue is stil reproducible with the same audio file. We tried on Friday from India and Sweden.
The results are quite good in Sweden (with 99% success rate) compared to that of in India.
We are running some more tests , will share you the results tomorrow.

Regards

**Comment by asergaz** [comment] 2020-12-15 01:16
@pvvpraveen @playboxsthlm as per the Azure Support Ticket closure reason:

"We are not able to reproduce this now... this might be due to bad network conditions that occur randomly."

Therefore I will request that @olivakar #please-close the issue and reopen if the issue occurs again.

Thank you for all your time!

**Comment by elhorton** [comment] 2021-01-15 18:19
Closing re: @asergaz 's comment above.

**Comment by az-iot-builder-01** [comment] 2021-01-15 18:19
@pvvpraveen, @asergaz, @playboxsthlm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2021-01-15 18:19 UTC
Labels: IoTSDK, bug, waiting-on-reply
